### ISSUE TITLE
Puppeteer issues while generating PhET-iO apis

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1022]
From https://github.com/phetsims/phet-io/issues/1733. I think it would be good to track this in a different issue.

Today, I was getting many "Navigation failed because browser has disconnected!" errors. I couldn't make it through generating a macro API for all phet-io sims:

```
 Michael ~/PhET/git/chipper (master)
 $ node js/phet-io/output-apis.js --simList=../perennial/data/phet-io
[.............                           ] 33.33%Error Error: Navigation failed because browser has disconnected!
    at C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:51:147
    at C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at CDPSession.emit (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at CDPSession._onClosed (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:247:14)
    at Connection._onMessage (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:94:25)
    at WebSocket.<anonymous> (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\node\NodeWebSocketTransport.js:13:32)
    at WebSocket.onMessage (C:\Users\Michael\PhET\git\chipper\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
[.....................................   ] 91.67%
 Michael ~/PhET/git/chipper (master)
 $ node js/phet-io/output-apis.js --simList=../perennial/data/phet-io
[..........                              ] 25.00%Error Error: Navigation failed because browser has disconnected!
    at C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:51:147
    at C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at CDPSession.emit (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at CDPSession._onClosed (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:247:14)
    at Connection._onMessage (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:94:25)
    at WebSocket.<anonymous> (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\node\NodeWebSocketTransport.js:13:32)
    at WebSocket.onMessage (C:\Users\Michael\PhET\git\chipper\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
[.............                           ] 33.33%
 Michael ~/PhET/git/chipper (master)
 $ node js/phet-io/output-apis.js --simList=../perennial/data/phet-io
[.......                                 ] 16.67%Error Error: Navigation failed because browser has disconnected!
    at C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:51:147
    at C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at CDPSession.emit (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at CDPSession._onClosed (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:247:14)
    at Connection._onMessage (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:94:25)
    at WebSocket.<anonymous> (C:\Users\Michael\PhET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\node\NodeWebSocketTransport.js:13:32)
    at WebSocket.onMessage (C:\Users\Michael\PhET\git\chipper\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
[..........                              ] 25.00%
 Michael ~/PhET/git/chipper (master)
 $ node js/phet-io/output-apis.js --simList=../perennial/data/phet-io-api-stable
[........................................] 100.00%

 Michael ~/PhET/git/chipper (master)

```

Tagging @samreid. It seems like this only happens on my windows git bash.

**Comment by samreid** [comment]
`https://github.com/alixaxel/chrome-aws-lambda/issues/104` suggested that a newer version of puppeteer may help?  We are currently on `^5.4.1` but the latest is 8.0.0.  It would be good to know if just upgrading the version helps (if there are no breaking changes), can you please test it?

**Comment by zepumph** [comment]
That issue brought me to `https://github.com/alixaxel/chrome-aws-lambda/issues/104#issuecomment-737474698` then I saw that in the general docs (https://www.npmjs.com/package/puppeteer/v/1.11.0-next.1547527073587), that `page.goto` is more often awaited. I feel like that may be similar to the `browser.setContent` cause. I will see if I encounter the error again after this change. 

Thoughts?

**Comment by samreid** [comment]
That looks like it's worth a try!  How long until we know if that's fixed?  If that doesn't fix it, should we try a new version?

**Comment by zepumph** [comment]
Just happened again:

```
Running "build" task
Building runnable repository (ratio-and-proportion, brands: phet-io, phet)
Building brand: phet-io
>> Webpack build complete: 2803ms
>> Production minification complete: 18342ms (1744344 bytes)
>> Debug minification complete: 13827ms (2013125 bytes)
>> No client guides found at ../phet-io-client-guides/ratio-and-proportion/, no guides being built.
Error [Error: Navigation failed because browser has disconnected!
  at C:\Users\Michael\PHET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:51:147
  at C:\Users\Michael\PHET\git\chipper\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
  at Array.map (<anonymous>:null:null)
  at Object.emit (C:\Users\Michael\PHET\git\chipper\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
  at CDPSession.emit (C:\Users\Michael\PHET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
  at CDPSession._onClosed (C:\Users\Michael\PHET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:247:14)
  at Connection._onMessage (C:\Users\Michael\PHET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:94:25)
  at WebSocket.<anonymous> (C:\Users\Michael\PHET\git\chipper\node_modules\puppeteer\lib\cjs\puppeteer\node\NodeWebSocketTransport.js:13:32)
  at WebSocket.onMessage (C:\Users\Michael\PHET\git\chipper\node_modules\ws\lib\event-target.js:132:16)
  at WebSocket.emit (events.js:315:20)
  at Receiver.receiverOnMessage (C:\Users\Michael\PHET\git\chipper\node_modules\ws\lib\websocket.js:825:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.dataMessage (C:\Users\Michael\PHET\git\chipper\node_modules\ws\lib\receiver.js:437:14)
  at Receiver.getData (C:\Users\Michael\PHET\git\chipper\node_modules\ws\lib\receiver.js:367:17)
  at Receiver.startLoop (C:\Users\Michael\PHET\git\chipper\node_modules\ws\lib\receiver.js:143:22)
  at Receiver._write (C:\Users\Michael\PHET\git\chipper\node_modules\ws\lib\receiver.js:78:10)
  at writeOrBuffer (_stream_writable.js:352:12)
  at Receiver.Writable.write (_stream_writable.js:303:10)
  at Socket.socketOnData (C:\Users\Michael\PHET\git\chipper\node_modules\ws\lib\websocket.js:900:35)
  at Socket.emit (events.js:315:20)
  at addChunk (_stream_readable.js:309:12)
  at readableAddChunk (_stream_readable.js:284:9)
  at Socket.Readable.push (_stream_readable.js:223:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
]
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: full api expected
  at module.exports (C:\Users\Michael\PHET\git\chipper\js\grunt\copySupplementalPhetioFiles.js:294:5)
  at module.exports (C:\Users\Michael\PHET\git\chipper\js\grunt\buildRunnable.js:355:5)
  at C:\Users\Michael\PHET\git\chipper\js\grunt\Gruntfile.js:255:11
  at wrap (C:\Users\Michael\PHET\git\chipper\js\grunt\Gruntfile.js:74:7)

Full Error details:
AssertionError [ERR_ASSERTION]: full api expected


```

**Comment by zepumph** [comment]
This issue has pretty much completely stopped for me. I'm going to close this, but please reopen if you ever get an error like "Navigation failed because browser has disconnected!"

**Comment by marlitas** [comment]
Looks like this is back in action for CCK-AC. 

```
Building brand: phet-io
>> Webpack build complete: 7437ms
>> Production minification complete: 43465ms (2866076 bytes)
>> Debug minification complete: 45301ms (3176222 bytes)
>> tsc complete: 6275ms
>> no client guide found at ../phet-io-sim-specific/repos/circuit-construction-kit-ac/examples.md, no guide being built.
>> tsc complete: 6153ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.
at module.exports (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1695405866252/chipper/js/grunt/copySupplementalPhetioFiles.js:385:5)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async module.exports (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1695405866252/chipper/js/grunt/buildRunnable.js:370:5)
at async /data/share/phet/continuous-testing/ct-main/ct-snapshots/1695405866252/chipper/js/grunt/Gruntfile.js:298:15
at async Object.startAsync (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1695405866252/perennial-alias/js/common/phetTimingLog.js:133:20)
at async /data/share/phet/continuous-testing/ct-main/ct-snapshots/1695405866252/chipper/js/grunt/Gruntfile.js:297:13
at async Object.startAsync (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1695405866252/perennial-alias/js/common/phetTimingLog.js:133:20)
at async /data/share/phet/continuous-testing/ct-main/ct-snapshots/1695405866252/chipper/js/grunt/Gruntfile.js:225:7
at async wrap (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1695405866252/chipper/js/grunt/Gruntfile.js:69:7)
Full Error details:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.

Error in fulfilling chunk Promise: [Error: TypeError: Yn(...) is not a function
at new zn (http://localhost:38227/circuit-construction-kit-ac/build/phet-io/circuit-construction-kit-ac_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1035:588885)
at 733 (http://localhost:38227/circuit-construction-kit-ac/build/phet-io/circuit-construction-kit-ac_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1035:880825)
at i (http://localhost:38227/circuit-construction-kit-ac/build/phet-io/circuit-construction-kit-ac_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1035:1143250)
at http://localhost:38227/circuit-construction-kit-ac/build/phet-io/circuit-construction-kit-ac_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1035:1144009
at http://localhost:38227/circuit-construction-kit-ac/build/phet-io/circuit-construction-kit-ac_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1035:2328403
at phet.chipper.runWebpack (http://localhost:38227/circuit-construction-kit-ac/build/phet-io/circuit-construction-kit-ac_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1035:2328407)
at i (http://localhost:38227/circuit-construction-kit-ac/build/phet-io/circuit-construction-kit-ac_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1036:1052)
at t (http://localhost:38227/circuit-construction-kit-ac/build/phet-io/circuit-construction-kit-ac_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1036:1080)
at http://localhost:38227/circuit-construction-kit-ac/build/phet-io/circuit-construction-kit-ac_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1036:1105
at http://localhost:38227/circuit-construction-kit-ac/build/phet-io/circuit-construction-kit-ac_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1036:1207]
Snapshot from 9/22/2023, 12:04:26 PM
```

Would love to get initial thoughts from @zepumph.

**Comment by zepumph** [comment]
I see that you got here from that assertion message. I'll take a look, it doesn't seem related to the original problem right from the start.

**Comment by marlitas** [comment]
Okay. I also see that it got triggered in phet-io-test-sim

```
phet-io-test-sim : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> tsc complete: 31091ms
Building runnable repository (phet-io-test-sim, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 8738ms
>> Production minification complete: 46101ms (2116670 bytes)
>> Debug minification complete: 0ms (20989409 bytes)
Building brand: phet-io
>> Webpack build complete: 8314ms
>> Production minification complete: 40384ms (2131421 bytes)
>> Debug minification complete: 40913ms (2425372 bytes)
>> tsc complete: 6364ms
>> tsc complete: 6283ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.
at module.exports (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1695425173878/chipper/js/grunt/copySupplementalPhetioFiles.js:385:5)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async module.exports (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1695425173878/chipper/js/grunt/buildRunnable.js:370:5)
at async /data/share/phet/continuous-testing/ct-main/ct-snapshots/1695425173878/chipper/js/grunt/Gruntfile.js:298:15
at async Object.startAsync (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1695425173878/perennial-alias/js/common/phetTimingLog.js:133:20)
at async /data/share/phet/continuous-testing/ct-main/ct-snapshots/1695425173878/chipper/js/grunt/Gruntfile.js:297:13
at async Object.startAsync (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1695425173878/perennial-alias/js/common/phetTimingLog.js:133:20)
at async /data/share/phet/continuous-testing/ct-main/ct-snapshots/1695425173878/chipper/js/grunt/Gruntfile.js:225:7
at async wrap (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1695425173878/chipper/js/grunt/Gruntfile.js:69:7)
Full Error details:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.

Error in fulfilling chunk Promise: [Error: TypeError: Right-hand side of 'instanceof' is not callable
at T.getRawStringValue (http://localhost:44371/phet-io-test-sim/build/phet-io/phet-io-test-sim_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1027:76552)
at http://localhost:44371/phet-io-test-sim/build/phet-io/phet-io-test-sim_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1027:76116
at Array.forEach (<anonymous>)
at T.getStateDelta (http://localhost:44371/phet-io-test-sim/build/phet-io/phet-io-test-sim_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1027:76091)
at http://localhost:44371/phet-io-test-sim/build/phet-io/phet-io-test-sim_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1027:77677
at Array.forEach (<anonymous>)
at Object.toStateObject (http://localhost:44371/phet-io-test-sim/build/phet-io/phet-io-test-sim_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1027:77655)
at p.toStateObject (http://localhost:44371/phet-io-test-sim/build/phet-io/phet-io-test-sim_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1027:1112773)
at W.getValueJSON (http://localhost:44371/phet-io-test-sim/build/phet-io/phet-io-test-sim_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1027:344121)
at http://localhost:44371/phet-io-test-sim/build/phet-io/phet-io-test-sim_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:1027:344709]
Snapshot from 9/22/2023, 5:26:13 PM
```

**Comment by zepumph** [comment]
I believe that this may be quite related to https://github.com/phetsims/aqua/issues/195 and race conditions on chipper dist/. Reclosing
