### ISSUE TITLE
Runtime error in `transpile.js`

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1161]
From discussion with @samreid, in regards to https://github.com/phetsims/chipper/issues/1156, I was asked to report failures in `transpile.js`. Here is one I had:

```
...
1265ms: ../greenhouse-effect\js\common\model\PhotonCollection.ts
40ms: ../joist\js\joistStrings.ts
77ms: ../number-play\js\numberPlayStrings.ts
internal/fs/utils.js:308
    throw err;
    ^

Error: ENOENT: no such file or directory, open '../perennial-alias\js\common\outputJS.js'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Transpiler.visitFile (C:\Users\Michael\PhET\git\chipper\js\common\Transpiler.js:104:23)
    at FSWatcher.<anonymous> (C:\Users\Michael\PhET\git\chipper\js\common\Transpiler.js:202:16)
    at FSWatcher.emit (events.js:315:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:186:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '../perennial-alias\\js\\common\\outputJS.js'
}

```

**Comment by samreid** [comment]
I added a fix that will hopefully help, closing.
