### ISSUE TITLE
Runtime error in transpile.js

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1162]
From discussion with @samreid, in regards to #1156, I was asked to report failures in transpile.js. Here is one I had:

```
. . . 
SyntaxError: C:\Users\Michael\PHET\git\bending-light\js\more-tools\view\SeriesCanvasNode.ts: Identifier 'NodeOptions' has already been declared. (15:9
)

  13 | import DataPoint from '../model/DataPoint.js';
  14 | import ModelViewTransform2 from '../../../../phetcommon/js/view/ModelViewTransform2.js';
> 15 | import { NodeOptions } from '../../../../scenery/js/nodes/Node.js';
     |          ^
  16 |
  17 | class SeriesCanvasNode extends CanvasNode {
  18 |   seriesProperty: Property<DataPoint[]>;
    at Object._raise (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:541:17)
    at Object.raiseWithData (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:534:17)
    at Object.raise (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:495:17)
    at TypeScriptScopeHandler.checkRedeclarationInScope (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\ind
ex.js:1690:12)
    at TypeScriptScopeHandler.declareName (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:1656:12)
    at TypeScriptScopeHandler.declareName (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7560:11)
    at Object.checkLVal (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11046:24)
    at Object.checkLVal (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:10025:15)
    at Object.parseImportSpecifier (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:14927:10)
    at Object.parseImportSpecifier (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:10274:18) {
  loc: Position { line: 15, column: 9 },
  pos: 555,
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'VarRedeclaration'
}
ERROR
SyntaxError: C:\Users\Michael\PHET\git\bending-light\js\more-tools\view\SeriesCanvasNode.ts: Identifier 'NodeOptions' has already been declared. (15:9
)

  13 | import DataPoint from '../model/DataPoint.js';
  14 | import ModelViewTransform2 from '../../../../phetcommon/js/view/ModelViewTransform2.js';
> 15 | import { NodeOptions } from '../../../../scenery/js/nodes/Node.js';
     |          ^
  16 |
  17 | class SeriesCanvasNode extends CanvasNode {
  18 |   seriesProperty: Property<DataPoint[]>;
    at Object._raise (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:541:17)
    at Object.raiseWithData (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:534:17)
    at Object.raise (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:495:17)
    at TypeScriptScopeHandler.checkRedeclarationInScope (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\ind
ex.js:1690:12)
    at TypeScriptScopeHandler.declareName (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:1656:12)
    at TypeScriptScopeHandler.declareName (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7560:11)
    at Object.checkLVal (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11046:24)
    at Object.checkLVal (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:10025:15)
    at Object.parseImportSpecifier (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:14927:10)
    at Object.parseImportSpecifier (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:10274:18) {
  loc: Position { line: 15, column: 9 },
  pos: 555,
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'VarRedeclaration'
}
ERROR
SyntaxError: C:\Users\Michael\PHET\git\bending-light\js\more-tools\view\SeriesCanvasNode.ts: Identifier 'NodeOptions' has already been declared. (15:9
)

  13 | import DataPoint from '../model/DataPoint.js';
  14 | import ModelViewTransform2 from '../../../../phetcommon/js/view/ModelViewTransform2.js';
> 15 | import { NodeOptions } from '../../../../scenery/js/nodes/Node.js';
     |          ^
  16 |
  17 | class SeriesCanvasNode extends CanvasNode {
  18 |   seriesProperty: Property<DataPoint[]>;
    at Object._raise (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:541:17)
    at Object.raiseWithData (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:534:17)
    at Object.raise (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:495:17)
    at TypeScriptScopeHandler.checkRedeclarationInScope (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\ind
ex.js:1690:12)
    at TypeScriptScopeHandler.declareName (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:1656:12)
    at TypeScriptScopeHandler.declareName (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7560:11)
    at Object.checkLVal (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11046:24)
    at Object.checkLVal (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:10025:15)
    at Object.parseImportSpecifier (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:14927:10)
    at Object.parseImportSpecifier (C:\Users\Michael\PHET\git\chipper\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:10274:18) {
  loc: Position { line: 15, column: 9 },
  pos: 555,
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'VarRedeclaration'
}
ERROR
1:31:29 PM, 64 ms: ../bending-light\js\more-tools\view\GridCanvasNode.ts
. . . 

```

This didn't crash the sim, but it did use the green color to present the error, and not each new line in the watch process is green. If we don't control the green color in errors, feel free to close.

**Comment by samreid** [comment]
I haven't adjusted or controlled the colors.  It seems babel caught a syntax error and the watch process didn't fail.  Should we close?
