### ISSUE TITLE
errors building locale-specific HTML files

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#119]
This was the case before doing the Gruntfile overhaul in #108.

`grunt --all-locales true`, for example, results in a lot of errors during the 'requirejs:build' task. Here's the console output for example-sim:

```
Running "requirejs:build" (requirejs) task
File doesn't exist:  /Volumes/b5 Data1/PhET/GitHub/example-sim/js/../strings/example-sim-strings_README.json
File doesn't exist:  /Volumes/b5 Data1/PhET/GitHub/example-sim/js/../strings/example-sim-strings_README.json
File doesn't exist:  /Volumes/b5 Data1/PhET/GitHub/joist/js/../strings/joist-strings_README.json
File doesn't exist:  /Volumes/b5 Data1/PhET/GitHub/joist/js/../strings/joist-strings_fr.json
File doesn't exist:  /Volumes/b5 Data1/PhET/GitHub/joist/js/../strings/joist-strings_README.json
F
...
```

Note that some of these files are example-sim, some are joist. And the same files are mentioned multiple times.

The build does continue and finishes, there are locale-specific HTML files in build/, and those HTML files appear to run.  So perhaps these are errors that can be safely ignored?

**Comment by pixelzoom** [comment]
I see the problem... In task beforeRequirejsBuild, global.phet.localesToBuild is set. For example-sim, its value is [ 'README', 'en', 'fr' ]. The 'README' is the culprit.  Looks like example-sim (and many other repos) have a README.txt file in theirs strings/ directory. The build task assumes that there's nothing in the directory but JSON string files.

**Comment by pixelzoom** [comment]
The README.txt files originated with simula-rasa. The build task should be smart enough to ignore non-string files, but I don't have time to do that now. So I will delete the README.txt files from simula-rasa and all other sim repos.

**Comment by pixelzoom** [comment]
OK, that go rid of the error messages related to "README".  Now we just have error messages related to joist.  I guess because the sim has string files for 'en' and 'fr', it's expecting that joist (and other common-code repos?) will also.  I don't think that's a correct expectation.

**Comment by pixelzoom** [comment]
I tried another sim (beers-law-lab) and it complains about both scenery-phet and joist files, then fails with SyntaxError:

```
% grunt build --all-locales true
...
File doesn't exist:  /Volumes/b5 Data1/PhET/GitHub/scenery-phet/js/../strings/scenery-phet-strings_ar.json
File doesn't exist:  /Volumes/b5 Data1/PhET/GitHub/scenery-phet/js/../strings/scenery-phet-strings_bs.json
File doesn't exist:  /Volumes/b5 Data1/PhET/GitHub/scenery-phet/js/../strings/scenery-phet-strings_da.json
File doesn't exist:  /Volumes/b5 Data1/PhET/GitHub/scenery-phet/js/../strings/scenery-phet-strings_de.json
...
File doesn't exist:  /Volumes/b5 Data1/PhET/GitHub/joist/js/../strings/joist-strings_ar.json
File doesn't exist:  /Volumes/b5 Data1/PhET/GitHub/joist/js/../strings/joist-strings_bs.json
File doesn't exist:  /Volumes/b5 Data1/PhET/GitHub/joist/js/../strings/joist-strings_da.json
File doesn't exist:  /Volumes/b5 Data1/PhET/GitHub/joist/js/../strings/joist-strings_de.json
...
>> Error: SyntaxError: Unexpected string
>> In module tree:
>>     beers-law-lab-main
>>       JOIST/Sim
>>         JOIST/NavigationBar
>>           JOIST/PhetButton
>>             JOIST/PhetMenu
>>               JOIST/AboutDialog
>> 
>>     at parse (native)
Warning: Task "requirejs:build" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by pixelzoom** [comment]
I'm stumped, not sure what's going on here. Guessing that fallback to English isn't happening properly for common-code strings.

**Comment by pixelzoom** [comment]
@samreid or @jonathanolson, any idea what might be wrong here?  The SyntaxError in https://github.com/phetsims/chipper/issues/119#issuecomment-85624127 doesn't point to the problem for me, perhaps it does for you.

**Comment by jonathanolson** [comment]
No errors for me on Linux or Windows. Only trying to build English in concentration/beers-law-lab.

Windows (SHAs from 30 mins ago):
```
$ grunt --all-locales true
Running "jshint:allFiles" (jshint) task
>> 474 files lint free.

Running "clean" task
Cleaning build directory

Running "generate-license-text" task
created license info for 10 dependencies

Running "before-requirejs-build" task
Building simulation: concentration 1.2.0-dev.1
Locales to build: en

Running "requirejs:build" (requirejs) task
>> RequireJS optimizer finished

c:/Users/jon/phet/git/concentration/build/concentration.min.js
Uncompressed size: 1899434 bytes.
Compressed size: 256929 bytes gzipped. (820134 bytes minified)

Running "after-requirejs-build" task
Minifying preload scripts
Copying changes.txt
Scanning dependencies from:
concentration,beers-law-lab,assert,axon,brand,chipper,dot,joist,kite,nitroglycerin,phet-core,phetcommon,scenery,scenery-phet,sherpa,sun
concentration       master 193f24c8dd0e72fb2e0e7af3b35571eab4f39c6f
beers-law-lab       master a99657a0fdf5699405798f9bda9ab8b63e6631bb
assert              master 952d1ea66d2aa4c707413ff3a355120a5fe0a6d4
axon                master 9d415eb95eac561226402535dbbeb34d611b514b
brand               master 8565ca68078fa1015fa677ee5ff8075508f0216b
chipper             master a37aaeb98e358dcb55c1d3d3d03799a406f429cf
dot                 master 300d500db2b269cef3a57afff6a484bd22b889c1
joist               master 005b2031cb244b29bad8ea3ec712993c9e46b809
kite                master 4283618986d554da85329ebdbc6c2ddd54cba84f
nitroglycerin       master c6f79ce4664a1120a8d1d2393d5d48f9b72d4bc9
phet-core           master 33450dabed3c9b3a2ed1c33666db534fb9e51fbc
phetcommon          master bb92c52cd90fdaa0c2a746fea82594afd439b4db
scenery             master 422ff322b6b4749406adad4293d6700932ecf49e
scenery-phet        master adbf7ffe7672f8321b4462a714b397146403e51e
sherpa              master 9a3ecfeeef516ec6361af14825f0581165625c44
sun                 master f290622fd4e3c6389779ce72fd32539b4d03ea72
Writing dependencies.json
Constructing HTML from template
Writing HTML
Constructing HTML for iframe testing from template
Writing HTML for iframe testing
Writing string map to  build/concentration_string-map.json
Cleaning temporary files
```

Linux (fresh pull, ignoring linting errors in beers-law-lab):
```
Running "jshint:allFiles" (jshint) task
Linting ../beers-law-lab/js/beerslaw/view/ConcentrationSlider.js ...ERROR
[L231:C67] W033: Missing semicolon.
      var delta = solution.concentrationTransform.viewToModel( 1 ) 

Warning: Task "jshint:allFiles" failed. Used --force, continuing.

Running "clean" task
Cleaning build directory

Running "generate-license-text" task
created license info for 10 dependencies

Running "before-requirejs-build" task
Building simulation: beers-law-lab 1.3.0-dev.2
Locales to build: en

Running "requirejs:build" (requirejs) task
>> RequireJS optimizer finished

/home/jon/phet/git/beers-law-lab/build/beers-law-lab.min.js
Uncompressed size: 1985566 bytes.
Compressed size: 326020 bytes gzipped. (962849 bytes minified)

Running "after-requirejs-build" task
Minifying preload scripts
Copying changes.txt
Scanning dependencies from:
beers-law-lab,assert,axon,brand,chipper,dot,joist,kite,nitroglycerin,phet-core,phetcommon,scenery,scenery-phet,sherpa,sun
beers-law-lab       master 47717ee77d10a8d6bcd5d92b92547865574c1ec6
assert              master 952d1ea66d2aa4c707413ff3a355120a5fe0a6d4
axon                master 9d415eb95eac561226402535dbbeb34d611b514b
brand               master 8565ca68078fa1015fa677ee5ff8075508f0216b
chipper             master a37aaeb98e358dcb55c1d3d3d03799a406f429cf
dot                 master 300d500db2b269cef3a57afff6a484bd22b889c1
joist               master 005b2031cb244b29bad8ea3ec712993c9e46b809
kite                master 4283618986d554da85329ebdbc6c2ddd54cba84f
nitroglycerin       master c6f79ce4664a1120a8d1d2393d5d48f9b72d4bc9
phet-core           master 33450dabed3c9b3a2ed1c33666db534fb9e51fbc
phetcommon          master bb92c52cd90fdaa0c2a746fea82594afd439b4db
scenery             master 422ff322b6b4749406adad4293d6700932ecf49e
scenery-phet        master adbf7ffe7672f8321b4462a714b397146403e51e
sherpa              master 9a3ecfeeef516ec6361af14825f0581165625c44
sun                 master f290622fd4e3c6389779ce72fd32539b4d03ea72
Writing dependencies.json
Constructing HTML from template
Writing HTML
Constructing HTML for iframe testing from template
Writing HTML for iframe testing
Writing string map to  build/beers-law-lab_string-map.json
Cleaning temporary files

Done, but with warnings.
```

**Comment by pixelzoom** [comment]
@jonathanolson Options to 'build' were changed, see https://github.com/phetsims/chipper/issues/124, and Skype announcement last Friday.  So what you are testing about is no different than `grunt`.

**Comment by pixelzoom** [comment]
You'll want to try `grunt --locales=*` to build all locales.  (Lint issues in BLL is fixed, btw.)

**Comment by jonathanolson** [comment]
Stack trace:
```
SyntaxError: Unexpected string
    at Object.parse (native)
    at eval (eval at <anonymous> (c:\Users\jon\phet\git\beers-law-lab\node_modules\requirejs\bin\r.js:25425:38), <anonymous>:196:33)
    at Object.load (eval at <anonymous> (c:\Users\jon\phet\git\beers-law-lab\node_modules\requirejs\bin\r.js:25425:38), <anonymous>:204:13)
    at Object.<anonymous> (c:\Users\jon\phet\git\beers-law-lab\node_modules\requirejs\bin\r.js:1311:28)
    at c:\Users\jon\phet\git\beers-law-lab\node_modules\requirejs\bin\r.js:372:23
    at on (c:\Users\jon\phet\git\beers-law-lab\node_modules\requirejs\bin\r.js:744:21)
    at Object.Module.callPlugin (c:\Users\jon\phet\git\beers-law-lab\node_modules\requirejs\bin\r.js:1173:17)
    at Object.moduleProto.callPlugin (c:\Users\jon\phet\git\beers-law-lab\node_modules\requirejs\bin\r.js:25512:42)
    at Object.Module.fetch (c:\Users\jon\phet\git\beers-law-lab\node_modules\requirejs\bin\r.js:1049:46)
    at Object.Module.check (c:\Users\jon\phet\git\beers-law-lab\node_modules\requirejs\bin\r.js:1079:26)
```

It looks like this failure initially occurs after attempting to load JOIST/Dialog, even though AboutDialog is listed. However removing the string declarations in AboutDialog causes OptionsDialog to be the one to trigger the error first.

The code eval()'ed for AboutDialog:

```js
define("JOIST/AboutDialog",["require","SCENERY/nodes/VBox","SCENERY/nodes/Text","PHET_CORE/inherit","SCENERY/input/ButtonListener","SCENERY_PHET/MultiLineText","SCENERY_PHET/PhetFont","PHETCOMMON/util/StringUtils","SUN/VStrut","JOIST/Dialog","SCENERY/input/Input","string!JOIST/credits.title","string!JOIST/credits.leadDesign","string!JOIST/credits.softwareDevelopment","string!JOIST/credits.team","string!JOIST/credits.qualityAssurance","string!JOIST/credits.graphicArts","string!JOIST/credits.translation","string!JOIST/credits.thanks","string!JOIST/versionPattern"]);
```

and for Dialog:

```js
define("JOIST/Dialog",["require","PHET_CORE/inherit","KITE/Shape","SCENERY/nodes/Node","SCENERY/nodes/Path","SUN/Panel","SUN/buttons/RectangularPushButton"]);
```

It's also worth noting that during normal builds, NONE of those evals are ever triggered. I haven't looked into it, but that seems weird to me. Next steps would hopefully be determining why require.js is taking such different code-paths for something that should be so similar.

**Comment by jonathanolson** [comment]
Also probably important for debugging, it's occurring in r.js for require.js 2.1.13.

**Comment by jonathanolson** [comment]
Going to bail on this for now. Manually editing the r.js file under node_modules has been the most helpful, with node-inspector being the second-most useful (stepping through errors after running node-debug causes timeouts for the 'env' module unfortunately).

**Comment by pixelzoom** [comment]
@jonathanolson thanks for taking a look. I'm also going to bail on this for now, defer until we address build issues for publishing translations.

**Comment by jonathanolson** [comment]
This was resolved by just recording which strings we'll need to handle while the string plugin is running, and then loading the files in the main build process (which is simpler overall). It's also Babel-compatible (working with Chains/Cadenas), fails on missing English strings, notifies about missing non-English (Babel) string files, and also ensures that all string repo dependencies are listed in the package.json's dependencies.

Reassigning to verify and if you would like, to review.

**Comment by pixelzoom** [comment]
Reassigning to @jonathanolson. Fails when specific locales are requested.

% cd chains
% grunt --locales=es
...
Fatal error: Cannot read property 'CHAINS/plainString' of undefined
%

**Comment by jonathanolson** [comment]
Fixed in changes, it looks like non-English builds still need access to English strings (that aren't fallbacks).

**Comment by pixelzoom** [comment]
Verified, closing.
