### ISSUE TITLE
Transpile watch breaks with checking out older code

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#1194]
An example that's reproducible

1. Clear chipper/dist (be on master for everything) -- skippable if you want to speed it up
2. In chipper: `node js/scripts/transpile.js --watch`
3. In perennial: `grunt checkout-timestamp --repo=friction --skipNpmUpdate --timestamp="Jan 15 2022 00:00:00"`

Breaks with:
```
10:47:25 AM, 8 ms: ../tambo/sounds/stepForwardV2_mp3.js (deleted)
10:47:25 AM, 7 ms: ../tambo/sounds/wallContact_mp3.js (deleted)
internal/fs/utils.js:259
    throw err;
    ^

Error: EPERM: operation not permitted, unlink '../chipper/dist/js/tambo/sounds/demo-and-test'
    at Object.unlinkSync (fs.js:1155:3)
    at FSWatcher.<anonymous> (/Users/jon/phet/git/chipper/js/common/Transpiler.js:236:14)
    at FSWatcher.emit (events.js:315:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:186:12) {
  errno: -1,
  syscall: 'unlink',
  code: 'EPERM',
  path: '../chipper/dist/js/tambo/sounds/demo-and-test'
}
```

**Comment by zepumph** [comment]
What server are you using? I'm on windows and often have things like this because my node http-server is holding on for dear life to a file. Stopping the server and rerunning the command fixes things for me.

**Comment by jonathanolson** [comment]
I'm definitely using the node http-server, interesting! Perhaps there's a global setting to allow more open files? I'll test this out soon.
