### ISSUE TITLE
CT marked is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/chipper#1282]
A number of repos in CT are failing with:
```
Fatal error: Perennial task failed:
TypeError: marked is not a function
```
Example:
```
gravity-force-lab : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> tsc complete: 81679ms
Building runnable repository (gravity-force-lab, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 27865ms
>> Unused string: key=a11y.voicing.briefDensityChangeForceAlertPattern, value={{densityChange}} density, {{forceChange}} forces.
>> Unused string: key=a11y.voicing.briefNewForcePattern, value=Forces now {{value}} newtons.
>> Unused string: key=a11y.voicing.briefMassChangeWithPushAlertPattern, value={{pushAlert}} {{forceAlert}}
>> Unused string: key=a11y.voicing.briefMassChangeAlertPattern, value={{propertyChange}} {{forceChange}}
>> Unused string: key=a11y.voicing.biggerCapitalized, value=Bigger
>> Unused string: key=a11y.voicing.smallerCapitalized, value=Smaller
>> Unused string: key=a11y.voicing.more, value=More
>> Unused string: key=a11y.voicing.less, value=Less
>> Unused string: key=a11y.voicing.levels.distanceArrowPattern, value={{distance}} kilometers
>> Production minification complete: 125857ms (3041308 bytes)
>> Debug minification complete: 0ms (22878371 bytes)
Building brand: phet-io
>> Webpack build complete: 22866ms
>> Unused string: key=a11y.voicing.briefDensityChangeForceAlertPattern, value={{densityChange}} density, {{forceChange}} forces.
>> Unused string: key=a11y.voicing.briefNewForcePattern, value=Forces now {{value}} newtons.
>> Unused string: key=a11y.voicing.briefMassChangeWithPushAlertPattern, value={{pushAlert}} {{forceAlert}}
>> Unused string: key=a11y.voicing.briefMassChangeAlertPattern, value={{propertyChange}} {{forceChange}}
>> Unused string: key=a11y.voicing.biggerCapitalized, value=Bigger
>> Unused string: key=a11y.voicing.smallerCapitalized, value=Smaller
>> Unused string: key=a11y.voicing.more, value=More
>> Unused string: key=a11y.voicing.less, value=Less
>> Unused string: key=a11y.voicing.levels.distanceArrowPattern, value={{distance}} kilometers
>> Production minification complete: 109224ms (3077636 bytes)
>> Debug minification complete: 115734ms (3394576 bytes)
No migration rules found at ../chipper/dist/js/phet-io-sim-specific/repos/gravity-force-lab/js/gravity-force-lab-migration-rules.js, no rules to be bundled with phet-io.js.
Fatal error: Perennial task failed:
TypeError: marked is not a function
at generateAndWriteClientGuide (/data/share/phet/continuous-testing/ct-snapshots/1657866327316/chipper/js/grunt/copySupplementalPhetioFiles.js:565:31)
at handleClientGuides (/data/share/phet/continuous-testing/ct-snapshots/1657866327316/chipper/js/grunt/copySupplementalPhetioFiles.js:535:3)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1657866327316/chipper/js/grunt/copySupplementalPhetioFiles.js:340:3)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async module.exports (/data/share/phet/continuous-testing/ct-snapshots/1657866327316/chipper/js/grunt/buildRunnable.js:356:5)
at async /data/share/phet/continuous-testing/ct-snapshots/1657866327316/chipper/js/grunt/Gruntfile.js:280:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1657866327316/chipper/js/grunt/Gruntfile.js:56:7)
Full Error details:
TypeError: marked is not a function
Snapshot from 7/15/2022, 12:25:27 AM
```

**Comment by zepumph** [comment]
Looks like @marlitas changed the version in https://github.com/phetsims/chipper/commit/6e09ba8aec16ef681d9c7be95297c97aef8f9465.

@marlitas can you please double check the API for the usage in copySupplementalPhetioFiles and test with `grunt --brands=phet-io` density since it has client guides (rendered using marked)?

https://github.com/phetsims/chipper/blob/22b3962ed4f3f9db6a90d2ebcadb3fade7166d02/js/grunt/copySupplementalPhetioFiles.js#L565

**Comment by marlitas** [comment]
Have not seen this error come up on CT since the above fix commits. Closing.
