### ISSUE TITLE
where is phet-io-wrapper?

### ISSUE THREAD

**Issue by 7dir** [phetsims/chipper#1303]
Fail to build sim 
```
mltefive@DESKTOP-PSCD36B MINGW64 /o/_prjs/dump/phetsims/example-sim (master)
$ grunt --brands=adapted-from-phet
Running "lint-all" task
[........................................] 100.00%

Running "report-media" task
skipping repo (not checked out): phet-io
skipping repo (not checked out): phet-io-sim-specific
skipping repo (not checked out): phet-io-wrappers
skipping repo (not checked out): studio

Running "clean" task

Running "build" task
Fatal error: Perennial task failed:
Error: ENOENT: no such file or directory, open '../chipper/dist/js/phet-io-wrappers/common/js/Client.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (o:\_prjs\dump\phetsims\chipper\js\grunt\copySupplementalPhetioFiles.js:85:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (o:\_prjs\dump\phetsims\chipper\js\grunt\buildRunnable.js:17:37)
Full Error details:
Error: ENOENT: no such file or directory, open '../chipper/dist/js/phet-io-wrappers/common/js/Client.js'
```

**Comment by samreid** [comment]
I fixed this as well as 2 downstream problems.  `grunt --brands=adapted-from-phet` seems to be working on my side now. 
 @7dir thanks for reporting it, would you like to pull all changes and test again?

**Comment by samreid** [comment]
This issue does appear resolved, so I will close it for now.  But @7dir please feel free to comment or repoen if the problem persists.

**Comment by 7dir** [comment]
Yeah! Thanks!

So I`d glone all repos.

My own script

```sh
for i in $(seq 7 $END); do curl https://api.github.com/users/phetsims/repos?page=$i -o phetsims_repos_page_$i.json ; done

rm -rf repos.txt
touch repos.txt
for i in $(seq 7 $END); do cat phetsims_repos_page_$i.json | grep full_name | awk -F '"' '{print($4)}' >> repos.txt ; done

clone_or_update () {
   echo "Parameter #1 is $1"
    if git clone https://github.com/phetsims/$1 ; then
        echo "clone"
    else
        echo "update"
        cd $1
        git pull
        cd ..
    fi
}

for i in `cat repos.txt`; do clone_or_update `echo $i | sed -e 's#phetsims/##g'`; done 
```

then

```sh
cd chipper
npm install
cd ../perennial
npm install
cd ..
cp -rf  perennial perennial-alias
```

`perennial-alias` is missing too but all works

```sh
$ cd waves-intro
$ npm install
$ grunt build --brands=adapted-from-phet --locales=uk
Running "build" task
skipping type checking
Building runnable repository (waves-intro, brands: adapted-from-phet)
Building brand: adapted-from-phet
>> Webpack build complete: 5562ms
>> WARNING404: Skipping potentially non-public dependency phet-io
>> WARNING404: Skipping potentially non-public dependency phet-io-sim-specific
>> WARNING404: Skipping potentially non-public dependency phet-io-wrappers
>> WARNING404: Skipping potentially non-public dependency studio
>> Production minification complete: 26143ms (2631488 bytes)
>> Debug minification complete: 0ms (22840693 bytes)

Done.
```
