### ISSUE TITLE
Running lint with brands=adapted-from-phet: Error: No files matching '../phet-io-sim-specific' were found.

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1322]
```
~/apache-document-root/main/gravity-and-orbits$ grunt --brands=adapted-from-phet
Running "lint-all" task
[.................                       ] 43.48%Fatal error: Perennial task failed:
Error: No files matching '../phet-io-sim-specific' were found.
    at FileEnumerator.iterateFiles (/Users/samreid/apache-document-root/main/chipper/node_modules/eslint/lib/cli-engine/file-enumerator.js:318:27)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (/Users/samreid/apache-document-root/main/chipper/node_modules/eslint/lib/cli-engine/cli-engine.js:786:48)
    at ESLint.lintFiles (/Users/samreid/apache-document-root/main/chipper/node_modules/eslint/lib/eslint/eslint.js:550:23)
    at lintOneRepo (/Users/samreid/apache-document-root/main/chipper/js/grunt/lint.js:95:32)
    at lint (/Users/samreid/apache-document-root/main/chipper/js/grunt/lint.js:137:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/samreid/apache-document-root/main/chipper/js/grunt/Gruntfile.js:357:29
    at async wrap (/Users/samreid/apache-document-root/main/chipper/js/grunt/Gruntfile.js:65:7)
Full Error details:
Error: No files matching '../phet-io-sim-specific' were found.
```

Discovered in https://github.com/phetsims/chipper/issues/1303

**Comment by samreid** [comment]
To accomplish this, I factored out a `getBrands` function.  Can this be reviewed please?  Should be quick. @zepumph are you available for this?

**Comment by samreid** [comment]
CT issue: 

```
/apache-document-root/main/dot$ grunt
Running "lint-all" task
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: dot does not appear to be runnable
    at getBrands (/Users/samreid/apache-document-root/main/chipper/js/grunt/Gruntfile.js:690:3)
    at /Users/samreid/apache-document-root/main/chipper/js/grunt/Gruntfile.js:338:20
    at Object.<anonymous> (/Users/samreid/apache-document-root/main/chipper/js/grunt/Gruntfile.js:94:13)
    at Object.thisTask.fn (/Users/samreid/apache-document-root/main/dot/node_modules/grunt/lib/grunt/task.js:70:16)
    at Object.<anonymous> (/Users/samreid/apache-document-root/main/dot/node_modules/grunt/lib/util/task.js:294:30)
    at Task.runTaskFn (/Users/samreid/apache-document-root/main/dot/node_modules/grunt/lib/util/task.js:244:24)
    at Task.<anonymous> (/Users/samreid/apache-document-root/main/dot/node_modules/grunt/lib/util/task.js:293:12)
    at /Users/samreid/apache-document-root/main/dot/node_modules/grunt/lib/util/task.js:220:11
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Full Error details:
AssertionError [ERR_ASSERTION]: dot does not appear to be runnable
```

**Comment by zepumph** [comment]
Looks great, thanks!
