### ISSUE TITLE
Build Error: ENOENT: no such file or directory, open '../chipper/dist/js/phet-io-wrappers/common/js/Client.js'

### ISSUE THREAD

**Issue by mattpen** [phetsims/chipper#1327]
```
Build failure: Error: Build aborted, Error: grunt --allHTML --debugHTML --brands=phet --locales=iw in ../build-a-nucleus failed with exit code 1
stdout:
Running "lint-all" task

[                                        ] 0.00%
[.                                       ] 3.57%
[...                                     ] 7.14%
[....                                    ] 10.71%
[......                                  ] 14.29%
[.......                                 ] 17.86%
[.........                               ] 21.43%
[..........                              ] 25.00%
[...........                             ] 28.57%
[.............                           ] 32.14%
[..............                          ] 35.71%
[................                        ] 39.29%
[.................                       ] 42.86%
[...................                     ] 46.43%
[....................                    ] 50.00%
[.....................                   ] 53.57%
[.......................                 ] 57.14%
[........................                ] 60.71%
[..........................              ] 64.29%
[...........................             ] 67.86%
[.............................           ] 71.43%
[..............................          ] 75.00%
[...............................         ] 78.57%
[.................................       ] 82.14%
[..................................      ] 85.71%
[....................................    ] 89.29%
[.....................................   ] 92.86%
[....................................... ] 96.43%
[........................................] 100.00%

Running "report-media" task

Running "clean" task

Running "build" task
Fatal error: Perennial task failed:
Error: ENOENT: no such file or directory, open '../chipper/dist/js/phet-io-wrappers/common/js/Client.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (/data/share/phet/build-server/chipper/js/grunt/copySupplementalPhetioFiles.js:85:12)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/data/share/phet/build-server/chipper/js/grunt/buildRunnable.js:17:37)
Full Error details:
Error: ENOENT: no such file or directory, open '../chipper/dist/js/phet-io-wrappers/common/js/Client.js'
. Sim = build-a-nucleus Version = 1.0.0 Brands = phet Locales = iw Shas = {"comment":"# build-a-nucleus 1.0.0 Sat Sep 10 2022 06:34:12 GMT-0600 (Mountain Daylight Time)","assert":{"sha":"c13a8c7741d95fbd8e37619c66ebcca8686dffe7","branch":"HEAD"},"axon":{"sha":"c74bd5abc5d6159c697866a1bc76651d2797ace0","branch":"HEAD"},"bamboo":{"sha":"2062e73a334fc1045e19ca33806834e229c31c74","branch":"HEAD"},"brand":{"sha":"643510ae84d6fb088b79e16154b925751951d854","branch":"HEAD"},"build-a-nucleus":{"sha":"1780999cb95f090bf69318fe1331843549f74ac2","branch":"HEAD"},"build-an-atom":{"sha":"f2051a89a3eb59557e2dd87def60373403be19d2","branch":"HEAD"},"chipper":{"sha":"f9cdfce5b7f40073f6a88d5e881fc4455d061f1a","branch":"HEAD"},"dot":{"sha":"beb462d7c0f8b9696454e821ac5ff188e9fecdfd","branch":"HEAD"},"joist":{"sha":"10baf354a310018bbe229c8e6f18cc0d2ea48c1f","branch":"HEAD"},"kite":{"sha":"4c6e3b939980ee8bb049cdbb62642a4561770fa0","branch":"HEAD"},"perennial-alias":{"sha":"9ed570727d0f61243ecd5cca269b0673be0cdf8d","branch":"HEAD"},"phet-core":{"sha":"d5bf67c048fa2e2bf2ae7bff6d08b2506e7a6f53","branch":"HEAD"},"phet-io":{"sha":"b0a733bd6cabdc78c56e335c3a06dcc42bbe13cf","branch":"HEAD"},"phet-io-sim-specific":{"sha":"1bf31a5c72d10377219b4635f223d7740734029f","branch":"HEAD"},"phet-io-wrappers":{"sha":"76970573eba48a5b7f9ccd221a0011067073dbbe","branch":"HEAD"},"phetcommon":{"sha":"2e1fed8da429f298dd3f1419353c377f22b3c9b3","branch":"HEAD"},"phetmarks":{"sha":"cff95352a6302a655292eba2c5850027957623cd","branch":"HEAD"},"query-string-machine":{"sha":"c17bdbf6f721bdde9460e6b8d6ad032a42bec35b","branch":"HEAD"},"scenery":{"sha":"5345d5634ffd7280a77fbb879cb46a754fa9dfb3","branch":"HEAD"},"scenery-phet":{"sha":"22a10979b2cbd4fc29edbc984cf3c7a705c0ae32","branch":"HEAD"},"sherpa":{"sha":"d3e3deeb273cf41e5b0bb563654b34f2c1a0ccf7","branch":"HEAD"},"shred":{"sha":"f2769b2c0117754c4e1da7b759c0d26ac53332b3","branch":"HEAD"},"studio":{"sha":"8c16b15ba11c356f8f94b0ed98837f75a410aa7c","branch":"HEAD"},"sun":{"sha":"468df7115a24dbdc9b98dd404eef3a4a1dcccdf0","branch":"HEAD"},"tambo":{"sha":"5672b124f6ef06839cb6dfe508f554b53ae2368c","branch":"HEAD"},"tandem":{"sha":"61da835b88cd6e5468c447a8c4827c9a631a0da1","branch":"HEAD"},"twixt":{"sha":"514228cf0f39d58ec753f21e36624ce52dc86cfb","branch":"HEAD"},"utterance-queue":{"sha":"ce62a902286b412c11c0b15b91446c51e971e29d","branch":"HEAD"}}

```

An `iw` translation failure for build-a-nucleus occurred today. I had deleted chipper/dist earlier in the day for https://github.com/phetsims/chipper/issues/1243#issuecomment-1242734368, I wonder if that could be related?

**Comment by samreid** [comment]
Looks related to https://github.com/phetsims/chipper/issues/1303

**Comment by samreid** [comment]
I published a maintenance release that fixes https://github.com/phetsims/chipper/issues/1303 and the RC and production build succeeded.  Not sure how to re-trigger the iw translation, @mattpen can you please advise?

**Comment by mattpen** [comment]
It looks like no translation re-trigger is needed, as the production build rebuilds all translations. The `iw` file and database entry are now both present on phet-server2. Closing.
