### ISSUE TITLE
explicit-method-return-type lint rule failure

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#1368]
Adding a function without a body causing the linter to throw an error like this
```
$ grunt lint
Running "lint" task
Fatal error: Perennial task failed:
TypeError: Cannot read properties of null (reading 'range')
Occurred while linting C:\Users\Jesse\Documents\Development\phetsims\quadrilateral\js\quadrilateral\model\Vertex.ts:168
Rule: "explicit-method-return-type"
    at Object.fix (C:\Users\Jesse\Documents\Development\phetsims\chipper\eslint\rules\explicit-method-return-type.js:96:49)
    at normalizeFixes (C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\eslint\lib\linter\report-translator.js:193:28)
    at C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\eslint\lib\linter\report-translator.js:364:49
    at Object.report (C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\eslint\lib\linter\linter.js:1086:41)
    at MethodDefinition (C:\Users\Jesse\Documents\Development\phetsims\chipper\eslint\rules\explicit-method-return-type.js:88:19)
    at ruleErrorHandler (C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\eslint\lib\linter\linter.js:1115:28)
    at C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\eslint\lib\linter\node-event-generator.js:297:26)
Full Error details:
TypeError: Cannot read properties of null (reading 'range')
Occurred while linting C:\Users\Jesse\Documents\Development\phetsims\quadrilateral\js\quadrilateral\model\Vertex.ts:168
Rule: "explicit-method-return-type"
```

It is coming from the fixer functions, I guess those are called eagerly.

https://github.com/phetsims/chipper/blob/83448d0fd088e76cffcdb2af9084287459c043e5/eslint/rules/explicit-method-return-type.js#L79

https://github.com/phetsims/chipper/blob/83448d0fd088e76cffcdb2af9084287459c043e5/eslint/rules/explicit-method-return-type.js#L96
Quick fix should be to return `false` early if node.body is undefined.

**Comment by jessegreenberg** [comment]
Fixed, no longer seeing this error when running lint (but still see expected errors when the method body hasn't been added yet).
