### ISSUE TITLE
CT: `Error: No files matching '../scenery-lab-demo' were found.`

### ISSUE THREAD

**Issue by veillette** [phetsims/chipper#1373]
```
code: 1
stdout:
Running "lint-everything" task
Fatal error: Perennial task failed:
Error: No files matching '../scenery-lab-demo' were found.
at FileEnumerator.iterateFiles (/data/share/phet/continuous-quick-server/chipper/node_modules/eslint/lib/cli-engine/file-enumerator.js:320:27)
at iterateFiles.next (<anonymous>)
at CLIEngine.executeOnFiles (/data/share/phet/continuous-quick-server/chipper/node_modules/eslint/lib/cli-engine/cli-engine.js:786:48)
at ESLint.lintFiles (/data/share/phet/continuous-quick-server/chipper/node_modules/eslint/lib/eslint/eslint.js:551:23)
at lintOneRepo (/data/share/phet/continuous-quick-server/chipper/js/grunt/lint.js:119:32)
at lint (/data/share/phet/continuous-quick-server/chipper/js/grunt/lint.js:169:27)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async /data/share/phet/continuous-quick-server/perennial/js/grunt/Gruntfile.js:544:31
at async wrap (/data/share/phet/continuous-quick-server/perennial/js/grunt/Gruntfile.js:44:7)
Full Error details:
Error: No files matching '../scenery-lab-demo' were found.

stderr:
```

**Comment by samreid** [comment]
Fixed, closing.
