### ISSUE TITLE
Variables should be declared on one line with a separate ‘var’ in front of each. 

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#390]
While I was working on the code review for bending light, I saw one of the style guidelines is:

> Variables should be declared on one line with a separate ‘var’ in front of each. 

We can now check for this using eslint's one-var rule.  I tested running grunt eslint using the "one-var" rule and saw 42 problems (when ran from bending-light).  I am inclined to add this as an eslint rule.

Sims can opt-out of this rule by commenting it out temporarily, but the better long term solution would be to bring our code up to speed.

**Comment by samreid** [comment]
@pixelzoom has published molarity and an RC for hookes-law, so I'm going to proceed with these changes in master.

**Comment by samreid** [comment]
@jbphet I recall you were going to publish some RCs soon.  We should be in touch about whether this issue will hamper your efforts.

**Comment by samreid** [comment]
Actually after yesterday's conversation, I'm still a bit unsure whether our common code master libs are "frozen" :ice_cream: Perhaps we should discuss it before I commit 42 fixes across various repos.  @jonathanolson @jbphet @pixelzoom @aaronsamuel137 @jessegreenberg please discuss below or we can discuss at next developer meeting.

**Comment by samreid** [comment]
Here's the lint rule we could add:

```js
    // permit only one var declaration per line, see #390
    "one-var": [2, "never"]
```

And here are the known issues it points out:

```
~/github/bending-light$ grunt
Running "eslint:allFiles" (eslint) task

/Users/samreid/github/chipper/js/requirejs-plugins/string.js
  95:7  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/dot/js/EigenvalueDecomposition.js
   34:5   error  Split 'var' declarations into multiple statements  one-var
  105:7   error  Split 'var' declarations into multiple statements  one-var
  126:7   error  Split 'var' declarations into multiple statements  one-var
  127:7   error  Split 'var' declarations into multiple statements  one-var
  245:7   error  Split 'var' declarations into multiple statements  one-var
  246:7   error  Split 'var' declarations into multiple statements  one-var
  367:7   error  Split 'var' declarations into multiple statements  one-var
  368:7   error  Split 'var' declarations into multiple statements  one-var
  461:7   error  Split 'var' declarations into multiple statements  one-var
  478:7   error  Split 'var' declarations into multiple statements  one-var
  479:7   error  Split 'var' declarations into multiple statements  one-var
  495:7   error  Split 'var' declarations into multiple statements  one-var
  850:13  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/dot/js/LUDecomposition.js
   19:5  error  Split 'var' declarations into multiple statements  one-var
  168:7  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/dot/js/Matrix.js
  318:7  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/dot/js/Matrix3.js
  785:7  error  Split 'var' declarations into multiple statements  one-var
  793:9  error  Split 'var' declarations into multiple statements  one-var
  839:9  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/dot/js/MatrixOps3.js
  426:7  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/dot/js/QRDecomposition.js
   31:5  error  Split 'var' declarations into multiple statements  one-var
  114:7  error  Split 'var' declarations into multiple statements  one-var
  145:7  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/dot/js/SingularValueDecomposition.js
  53:5  error  Split 'var' declarations into multiple statements  one-var
  54:5  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/kite/js/Shape.js
  658:7  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/scenery/js/display/RelativeTransform.js
  449:7  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/scenery/js/display/SVGSelfDrawable.js
  73:9  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/scenery/js/nodes/Node.js
  1903:7  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/scenery/js/nodes/Rectangle.js
  486:5  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/scenery/js/util/Color.js
  352:7  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/scenery/js/util/Util.js
  274:7  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/scenery-phet/js/CurvedArrowShape.js
  59:5  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/scenery-phet/js/ParametricSpringNode.js
  113:5  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/scenery-phet/js/ScientificNotationNode.js
  130:7  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/scenery-phet/js/SubSupText.js
  83:7  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/scenery-phet/js/VisibleColor.js
  32:5  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/scenery-phet/js/WavelengthSlider.js
  165:5  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/sun/js/AccordionBox.js
  165:5  error  Split 'var' declarations into multiple statements  one-var

/Users/samreid/github/sun/js/ComboBox.js
  146:5  error  Split 'var' declarations into multiple statements  one-var
  223:7  error  Split 'var' declarations into multiple statements  one-var

✖ 42 problems (42 errors, 0 warnings)
```

**Comment by pixelzoom** [comment]
@samreid said:
> I'm still a bit unsure whether our common code master libs are "frozen"

I believe that we were considering using the shas from molarity to publish other sims.  One flaw in that strategy will be if a sim requires a repo that molarity did not (e.g., vegas, vibe,...)

Expressed as a shell script (untested) the strategy would be:

```
# Checkout molarity and its dependencies which have been vetted
cd molarity
git checkout 1.2
grunt checkout-shas

# Put someSim on the proper branch
cd ../someSim
git checkout someBranch

# Edit version in package.json here

# Build and publish someSim
grunt
grunt deploy-production

# Now return everything to master
grunt checkout-master
git checkout master
cd ../molarity
git checkout master
```

**Comment by jbphet** [comment]
Consensus from 10/20/2015 meeting is to turn on this lint rule and start fixing the issues.  @samreid will fix initially and turn on the rule once the issue has been fixed everywhere in the code base.

**Comment by samreid** [comment]
I addressed a number of these issues yesterday, will commit shortly.  Still to do:

* half of the repos
* add the rule to chipper
* run fuzz tests to make sure nothing was disturbed

**Comment by samreid** [comment]
Fixed all known issues and committed above.  Last step here is for me to run fuzzer tests and make sure no syntactic errors were accidentally introduced.

**Comment by samreid** [comment]
grunt-all lint succeeds for everything.  I am seeing these issues reported in the requirejs fuzz tester:

```
beaker
Uncaught TypeError: wrapper.setFillStyle is not a function
TypeError: wrapper.setFillStyle is not a function
    at ParticlesNode.inherit.paintCanvas (http://localhost:8080/beaker/js/beaker/view/ParticlesNode.js?bust=1445827013574:54:17)
    at CanvasNodeDrawable.inherit.paintCanvas (http://localhost:8080/scenery/js/nodes/CanvasNode.js?bust=1445827013574:128:14)
    at CanvasBlock.inherit.renderDrawable (http://localhost:8080/scenery/js/display/CanvasBlock.js?bust=1445827013574:172:16)
    at CanvasBlock.inherit.update (http://localhost:8080/scenery/js/display/CanvasBlock.js?bust=1445827013574:123:16)
    at BackboneDrawable.inherit.update (http://localhost:8080/scenery/js/display/BackboneDrawable.js?bust=1445827013574:242:37)
    at DOMBlock.inherit.update (http://localhost:8080/scenery/js/display/DOMBlock.js?bust=1445827013574:47:26)
    at BackboneDrawable.inherit.update (http://localhost:8080/scenery/js/display/BackboneDrawable.js?bust=1445827013574:242:37)
    at Display.extend.updateDisplay (http://localhost:8080/scenery/js/display/Display.js?bust=1445827013574:338:26)
    at Sim.inherit.stepSimulation (http://localhost:8080/joist/js/Sim.js?bust=1445827013574:750:20)
    at Sim.inherit.runAnimationLoop (http://localhost:8080/joist/js/Sim.js?bust=1445827013574:674:12)
beaker
Uncaught Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at Display.extend.ensureNotPainting (http://localhost:8080/scenery/js/display/Display.js?bust=1445827013574:1026:17)
    at CanvasBlock.inherit.markDirtyDrawable (http://localhost:8080/scenery/js/display/CanvasBlock.js?bust=1445827013574:196:22)
    at CanvasNodeDrawable.inherit.markDirty (http://localhost:8080/scenery/js/display/Drawable.js?bust=1445827013574:264:31)
    at ParticlesNode.inherit.invalidatePaint (http://localhost:8080/scenery/js/nodes/CanvasNode.js?bust=1445827013574:66:30)
    at Array. (http://localhost:8080/beaker/js/beaker/view/ParticlesNode.js?bust=1445827013574:33:16)
    at ShakerParticles.inherit.fireParticlesChanged (http://localhost:8080/beaker/js/beaker/model/ShakerParticles.js?bust=1445827013574:161:30)
    at ShakerParticles.inherit.step (http://localhost:8080/beaker/js/beaker/model/ShakerParticles.js?bust=1445827013574:125:14)
    at BeakerModel.inherit.propagateShakerParticles (http://localhost:8080/beaker/js/beaker/model/BeakerModel.js?bust=1445827013574:266:28)
    at BeakerModel.inherit.step (http://localhost:8080/beaker/js/beaker/model/BeakerModel.js?bust=1445827013574:134:12)
least-squares-regression
Uncaught Error: Assertion failed: Segment end is infinite
Error: Assertion failed: Segment end is infinite
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at Subpath.inherit.addSegmentDirectly (http://localhost:8080/kite/js/util/Subpath.js?bust=1445828653112:104:17)
    at http://localhost:8080/kite/js/util/Subpath.js?bust=1445828653112:120:17
    at Function.St (http://localhost:8080/sherpa/lib/lodash-2.4.1.min.js?bust=1445828653112:23:149)
    at Subpath.inherit.addSegment (http://localhost:8080/kite/js/util/Subpath.js?bust=1445828653112:119:9)
    at Shape.inherit.addSegmentAndBounds (http://localhost:8080/kite/js/Shape.js?bust=1445828653112:784:29)
    at Shape.inherit.lineToPoint (http://localhost:8080/kite/js/Shape.js?bust=1445828653112:146:14)
    at Shape.inherit.lineTo (http://localhost:8080/kite/js/Shape.js?bust=1445828653112:136:44)
    at HSlider.inherit.addTick (http://localhost:8080/sun/js/HSlider.js?bust=1445828653112:262:12)
    at new VerticalSlider (http://localhost:8080/least-squares-regression/js/least-squares-regression/view/MyLineControlPanel.js?bust=1445828653112:61:16)
pendulum-lab
Uncaught Error: Assertion failed: NavigationBar icons for screen 0 did not have a valid aspect ratio.
Error: Assertion failed: NavigationBar icons for screen 0 did not have a valid aspect ratio.
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at new NavigationBar (http://localhost:8080/joist/js/NavigationBar.js?bust=1445828925246:74:19)
    at new Sim (http://localhost:8080/joist/js/Sim.js?bust=1445828925246:373:25)
    at http://localhost:8080/pendulum-lab/js/pendulum-lab-main.js?bust=1445828925246:41:15
    at doneLoadingImages (http://localhost:8080/joist/js/SimLauncher.js?bust=1445828925246:33:9)
    at Object.launch (http://localhost:8080/joist/js/SimLauncher.js?bust=1445828925246:53:9)
    at http://localhost:8080/pendulum-lab/js/pendulum-lab-main.js?bust=1445828925246:40:15
    at Object.context.execCb (http://localhost:8080/sherpa/lib/require-2.1.11.js:1650:25)
    at Object.Module.check (http://localhost:8080/sherpa/lib/require-2.1.11.js:866:35)
    at Object. (http://localhost:8080/sherpa/lib/require-2.1.11.js:1113:20)
rutherford-scattering
Uncaught Error: Assertion failed: undefined
Error: Assertion failed: undefined
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at Node.extend.setVisible (http://localhost:8080/scenery/js/nodes/Node.js?bust=1445829137433:2343:17)
    at http://localhost:8080/sun/js/ToggleNode.js?bust=1445829137433:44:22
    at Property.inherit.link (http://localhost:8080/axon/js/Property.js?bust=1445829137433:171:11)
    at new ToggleNode (http://localhost:8080/sun/js/ToggleNode.js?bust=1445829137433:43:21)
    at PlayPauseButton.BooleanRoundToggleButton [as constructor] (http://localhost:8080/sun/js/buttons/BooleanRoundToggleButton.js?bust=1445829137433:22:86)
    at new PlayPauseButton (http://localhost:8080/scenery-phet/js/buttons/PlayPauseButton.js?bust=1445829137433:61:30)
    at new AnimationControlView (http://localhost:8080/rutherford-scattering/js/rutherford-atom/view/AnimationControlView.js?bust=1445829137433:29:27)
    at new RutherfordAtomView (http://localhost:8080/rutherford-scattering/js/rutherford-atom/view/RutherfordAtomView.js?bust=1445829137433:57:20)
    at RutherfordAtomScreen.Screen.call.backgroundColor [as createView] (http://localhost:8080/rutherford-scattering/js/rutherford-atom/RutherfordAtomScreen.js?bust=1445829137433:34:34)
states-of-matter
Uncaught Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at Display.extend.ensureNotPainting (http://localhost:8080/scenery/js/display/Display.js?bust=1445829228910:1026:17)
    at BackboneDrawable.inherit.markDirtyDrawable (http://localhost:8080/scenery/js/display/BackboneDrawable.js?bust=1445829228910:209:22)
    at SVGBlock.inherit.markDirty (http://localhost:8080/scenery/js/display/Drawable.js?bust=1445829228910:264:31)
    at SVGBlock.inherit.markDirtyGroup (http://localhost:8080/scenery/js/display/SVGBlock.js?bust=1445829228910:158:12)
    at SVGGroup.inherit.markDirty (http://localhost:8080/scenery/js/display/SVGGroup.js?bust=1445829228910:121:20)
    at SVGGroup.inherit.markVisibilityDirty (http://localhost:8080/scenery/js/display/SVGGroup.js?bust=1445829228910:153:14)
    at ArrowNode.axon.Events.trigger0 (http://localhost:8080/axon/js/Events.js?bust=1445829228910:280:29)
    at ArrowNode.extend.setVisible (http://localhost:8080/scenery/js/nodes/Node.js?bust=1445829228910:2351:14)
    at InteractionCanvasNode.inherit.paintCanvas (http://localhost:8080/states-of-matter/js/common/view/InteractionPotentialCanvasNode.js?bust=1445829228910:90:46)
states-of-matter
Uncaught Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at Display.extend.ensureNotPainting (http://localhost:8080/scenery/js/display/Display.js?bust=1445829228910:1026:17)
    at BackboneDrawable.inherit.markDirtyDrawable (http://localhost:8080/scenery/js/display/BackboneDrawable.js?bust=1445829228910:209:22)
    at SVGBlock.inherit.markDirty (http://localhost:8080/scenery/js/display/Drawable.js?bust=1445829228910:264:31)
    at SVGBlock.inherit.markDirtyGroup (http://localhost:8080/scenery/js/display/SVGBlock.js?bust=1445829228910:158:12)
    at SVGGroup.inherit.markDirty (http://localhost:8080/scenery/js/display/SVGGroup.js?bust=1445829228910:121:20)
    at SVGGroup.inherit.markVisibilityDirty (http://localhost:8080/scenery/js/display/SVGGroup.js?bust=1445829228910:153:14)
    at HighlightNode.axon.Events.trigger0 (http://localhost:8080/axon/js/Events.js?bust=1445829228910:280:29)
    at HighlightNode.extend.setVisible (http://localhost:8080/scenery/js/nodes/Node.js?bust=1445829228910:2351:14)
    at HighlightNode.visible (http://localhost:8080/scenery/js/nodes/Node.js?bust=1445829228910:2355:33)
states-of-matter
Uncaught Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at Display.extend.ensureNotPainting (http://localhost:8080/scenery/js/display/Display.js?bust=1445829228910:1026:17)
    at CanvasBlock.inherit.markDirtyDrawable (http://localhost:8080/scenery/js/display/CanvasBlock.js?bust=1445829228910:196:22)
    at CanvasNodeDrawable.inherit.markDirty (http://localhost:8080/scenery/js/display/Drawable.js?bust=1445829228910:264:31)
    at ParticleCanvasNode.inherit.invalidatePaint (http://localhost:8080/scenery/js/nodes/CanvasNode.js?bust=1445829228910:66:30)
    at ParticleCanvasNode.inherit.step (http://localhost:8080/states-of-matter/js/common/view/ParticleCanvasNode.js?bust=1445829228910:85:12)
    at PhaseChangesScreenView.inherit.step (http://localhost:8080/states-of-matter/js/phase-changes/view/PhaseChangesScreenView.js?bust=1445829228910:269:27)
    at Sim.inherit.stepSimulation (http://localhost:8080/joist/js/Sim.js?bust=1445829228910:738:25)
    at Sim.inherit.runAnimationLoop (http://localhost:8080/joist/js/Sim.js?bust=1445829228910:674:12)
```

None of them seem directly attributable to the changes in this issue, but I'll leave this issue open until those items are fixed or reported elsewhere.

**Comment by jbphet** [comment]
The beaker issue is known and has a fix waiting on a branch - I just didn't want to mess with the upcoming release for this sim.  The SOM issue is also known and is due to some recent changes in Scenery.  Both should be fixed today.

**Comment by samreid** [comment]
OK I think all issues are tracked elsewhere.  I created an issue for https://github.com/phetsims/states-of-matter/issues/111 before reading @jbphet message, sorry if it is duplicate!

I also found that common code repos weren't hit by grunt-all lint, so I will still need to do dot/kite/scenery/axon/etc.  I've removed the rule from chipper for now.

**Comment by samreid** [comment]
OK I fixed common code issues and re-enabled the rule.  Last step is to do one last requirejs fuzz test and make sure nothing was disrupted.

**Comment by samreid** [comment]
I should also mention that grunt-all.sh lint-all is passing for all sims now, with the new var rule.

**Comment by samreid** [comment]
Requirejs fuzz tests complete, no new issues discovered.  Closing.
