### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#500]
Yesterday @jonathanolson identified that one of our new dependencies requires a newer node/npm than the one he previously had.

Here are my npm/node versions which are known to work:
```
[9/26/16, 12:39:11 PM] Sam Reid: ~/github/molecule-shapes$ npm --version
3.10.7
[9/26/16, 12:39:18 PM] Sam Reid: ~/github/molecule-shapes$ node --version
v4.2.1
```

Here are @jonathanolson node/npm versions which are known to not work:
```
:~/phet/git/molecule-shapes # npm --version
1.4.9
:~/phet/git/molecule-shapes # node --version
v0.10.28
```

Here is our transcript:

[9/26/16, 12:33:15 PM] Jonathan Olson: btw, am I missing some lint commits from dot/kite related to extra break statements? I don't mind fixing them at all, just grunt lint is failing out for a sim
[9/26/16, 12:33:34 PM] Jonathan Olson: my apologies if somehow my repos aren't up to date, but I did pull everything
[9/26/16, 12:33:35 PM] Sam Reid: which sim?
[9/26/16, 12:33:41 PM] Jonathan Olson: molecule-shapes was the one I tested
[9/26/16, 12:33:45 PM] Sam Reid: testing...
[9/26/16, 12:35:09 PM] Sam Reid: what is your eslint version?
[9/26/16, 12:35:25 PM] Jonathan Olson: bah, let me wipe node_modules
[9/26/16, 12:37:07 PM] Jonathan Olson: not sure how to tell, but now:

/Users/jon/phet/git/molecule-shapes/node_modules/grunt-eslint/tasks/eslint.js:2
const chalk = require('chalk');
^^^^^
Loading "eslint.js" tasks...ERROR
>> SyntaxError: Use of const in strict mode.
Warning: Task "eslint:allFiles" not found. Use --force to continue.

Aborted due to warnings.
[9/26/16, 12:37:26 PM] Sam Reid: You got some ES6 code in there?
[9/26/16, 12:37:36 PM] Jonathan Olson: wiped chipper and molecule-shapes' node_modules and re-npm-installed
[9/26/16, 12:37:40 PM] Jonathan Olson: I dont think so
[9/26/16, 12:38:04 PM] Jonathan Olson: is my node itself too old or something?
[9/26/16, 12:38:16 PM] Sam Reid: I’m not sure what the trouble is.  Can you Skype me the lint errors?
[9/26/16, 12:38:26 PM] Jonathan Olson: that's now the only error (that it shows)
[9/26/16, 12:38:45 PM] Sam Reid: > related to extra break statements?
[9/26/16, 12:38:51 PM] Sam Reid: oh I see
[9/26/16, 12:38:55 PM] Jonathan Olson: those went away when I wiped node_modules
[9/26/16, 12:38:59 PM] Jonathan Olson: replaced by just that error
[9/26/16, 12:39:11 PM] Sam Reid: ~/github/molecule-shapes$ npm --version
3.10.7
[9/26/16, 12:39:18 PM] Sam Reid: ~/github/molecule-shapes$ node --version
v4.2.1
[9/26/16, 12:39:23 PM] Jonathan Olson: silver:~/phet/git/molecule-shapes # npm --version
1.4.9
silver:~/phet/git/molecule-shapes # node --version
v0.10.28
silver:~/phet/git/molecule-shapes #
[9/26/16, 12:39:56 PM] Jonathan Olson: I'll look into updating then
[9/26/16, 12:40:00 PM] Sam Reid: ~/github/molecule-shapes$ node node_modules/eslint/bin/eslint.js --version
v3.6.0
[9/26/16, 12:40:17 PM] Sam Reid: That may help if you have a node that is too old for const.
[9/26/16, 12:40:38 PM] Jonathan Olson: Error: Cannot find module '/Users/jon/phet/git/molecule-shapes/node_modules/eslint/bin/eslint.js'
[9/26/16, 12:40:43 PM] Jonathan Olson: file doesn't exist
[9/26/16, 12:40:49 PM] Jonathan Olson: no node_modules/eslint
[9/26/16, 12:40:53 PM] Sam Reid: hmmm
[9/26/16, 12:41:00 PM] Jonathan Olson: package.json doesn't mention it
[9/26/16, 12:41:12 PM] Sam Reid: it is a dependency of grunt-eslint
[9/26/16, 12:41:26 PM] Jonathan Olson: which would be nested under grunt-eslint/node_modules in my version of node
[9/26/16, 12:41:35 PM] Sam Reid: ah I see… checking...
[9/26/16, 12:42:00 PM] Jonathan Olson: found the file
[9/26/16, 12:42:01 PM] Jonathan Olson: silver:~/phet/git/molecule-shapes # node node_modules/grunt-eslint/node_modules/eslint/bin/eslint.js --version

/Users/jon/phet/git/molecule-shapes/node_modules/grunt-eslint/node_modules/eslint/lib/cli.js:18
const fs = require("fs"),
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jon/phet/git/molecule-shapes/node_modules/grunt-eslint/node_modules/eslint/bin/eslint.js:29:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
[9/26/16, 12:42:12 PM] Jonathan Olson: ok, so I'll look into upgrading node/npm
[9/26/16, 12:42:19 PM] Jonathan Olson: presumably should fix it
[9/26/16, 12:42:20 PM] Jonathan Olson: thanks!
[9/26/16, 12:42:22 PM] Sam Reid: I hope so!

**Comment by samreid** [comment]
In the above thread, @jonathanolson and I concluded that the next step would be to see if a newer version of npm and node would solve the problem.  I haven't heard from @jonathanolson about whether that was confirmed.

**Comment by samreid** [comment]
@phet-steele reported:

> I’m trying to run the automated test this morning but this is happening on every sim:

```
Loading "eslint.js" tasks...ERROR
>> SyntaxError: Use of const in strict mode.
Warning: Task "eslint:allFiles" not found. Use --force to continue.
```

**Comment by samreid** [comment]
I'm unaware how to log in to the test-server or where on its hard drive things are located.  @jonathanolson can you help?

**Comment by samreid** [comment]
I emailed the developer list:

> After pulling changes to package.json, you may need to make sure you a recent enough version of node/npm to recognize "const" syntax.  Please see https://github.com/phetsims/chipper/issues/500 for details.

> Sam

**Comment by samreid** [comment]
I also emailed:

Also, build-server and test-server will need to be updated as well.

Jon, can you update test-server?  Also are credentials written somewhere so that in the future I could take care of that?

Matt or John, can you update build-server?

Best Regards,
Sam

**Comment by jonathanolson** [comment]
Updated node/npm on phettest:
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
sudo npm install -g npm
```
Should be able to do ```sudo n stable``` and ```sudo npm install -g npm``` to update if necessary in the future.

**Comment by samreid** [comment]
I'll assign to @mattpen to make sure the build servers ox and ox-dev are up-to date.

**Comment by jonathanolson** [comment]
The above works on OSX also.

**Comment by mattpen** [comment]
```
[root@phet-server perennial]# node --version
v4.5.0
[root@phet-server perennial]# npm --version
2.15.9
```

node/npm were updated on phet-server and phet-server-dev tonight, and I restarted rosetta and build-server afterwards without error.  The servers were previously running node v0.10.X, but v4.X.X should be backwards compatible.
