### ISSUE TITLE
Updating node broke npm

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#534]
~/github/faradays-law$ node --version
v7.0.0
~/github/faradays-law$ brew update
...
~/github/faradays-law$ brew upgrade node
==> Upgrading 1 outdated package, with result:
node 7.3.0
==> Upgrading node 
==> Downloading https://homebrew.bintray.com/bottles/node-7.3.0.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring node-7.3.0.sierra.bottle.tar.gz
==> Using the sandbox
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall node`
==> Caveats
Please note by default only English locale support is provided. If you need
full locale support you should either rebuild with full icu:
  `brew reinstall node --with-full-icu`
or add full icu data at runtime following:
  https://github.com/nodejs/node/wiki/Intl#using-and-customizing-the-small-icu-build

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/7.3.0: 3,892 files, 45.5M
~/github/faradays-law$ node --version
v7.3.0
~/github/faradays-law$ npm install -g npm
module.js:472
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:75:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
~/github/faradays-law$ npm --version
module.js:472
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:75:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by samreid** [comment]
I'm following https://gist.github.com/DanHerbert/9520689 as a potential fix.

**Comment by samreid** [comment]
I deleted my node directories and reinstalled, it seems to be working now.
