### ISSUE TITLE
Upgrade to Node > v0.8

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#64]
Looks like https://github.com/isaacs/minimatch/issues/35 is giving us problems, ran into "npm install" failures on Win/Mac tonight:

```
npm ERR! Error: No compatible version found: minimatch@'^0.3.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.4","0.0.5","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.2.0","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2
.9","0.2.10","0.2.11","0.2.12","0.2.13","0.2.14","0.3.0"]
npm ERR!     at installTargetsError (c:\Program Files\nodejs\node_modules\npm\lib\cache.js:674:10)
npm ERR!     at c:\Program Files\nodejs\node_modules\npm\lib\cache.js:589:10
npm ERR!     at saved (c:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at c:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:169:16
npm ERR!     at fs.writeFile (fs.js:746:21)
npm ERR!     at c:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:53:5
npm ERR!     at c:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:62:5
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Users\jon\phet\git\optics-lab
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
```

I'd recommend updating node.js or copying over node_modules from a previously-working repo's directory for now. (I have 0.10.28 now).

**Comment by pixelzoom** [comment]
@jonathanolson is this still an issue?

**Comment by jonathanolson** [comment]
Not still an issue.
