### ISSUE TITLE
TypeError: buildLocal.brands.filter is not a function

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#640]
This is a small edge case, but may be worth a log statement or type check. 

```
Running "build" task
TypeError: buildLocal.brands.filter is not a function
  at Object.<anonymous> (E:\zepumph\Programming\PHET\git\chipper\js\grunt\Gruntfile.js:101:40)
  at Object.thisTask.fn (E:\zepumph\Programming\PHET\git\faradays-law\node_modules\grunt\lib\grunt\task.js:73:16)
  at Object.<anonymous> (E:\zepumph\Programming\PHET\git\faradays-law\node_modules\grunt\lib\util\task.js:294:30)
  at Task.runTaskFn (E:\zepumph\Programming\PHET\git\faradays-law\node_modules\grunt\lib\util\task.js:244:24)
  at Task.<anonymous> (E:\zepumph\Programming\PHET\git\faradays-law\node_modules\grunt\lib\util\task.js:293:12)
  at E:\zepumph\Programming\PHET\git\faradays-law\node_modules\grunt\lib\util\task.js:220:11
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)

```
This is the error that you get if you have a `brands` field in build-local.json,  but it is the wrong type. I wrote `"brands":"phet,phet-io", . . .` and got this error because it expected an array. Perhaps a check to make sure that the brands field is the correct type before using the value. Assigning @jonathanolson to work on at the priority he thinks is best.

**Comment by jonathanolson** [comment]
Added an assertion, closing.
