### ISSUE TITLE
Should chipper 2.0 ever release an rc.0?

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#685]
When chains was on master at `1.16.0-dev.*`, @samreid and I did the following command:

` $ grunt rc --brands=phet-io,phet --branch=1.17`

We were surprised to see that it proceeded to try to deploy `1.17.0-rc.0`. Is that correct?

Here is another problem (it should probably be in another issue): furthermore, when I wasn't on vpn, it didn't create/deploy rc.0, but kept it in the package.json when the process failed out, so the next time, when I ran the same command, it tried to deploy rc.1. 

Shouldn't the process have reverted rc.0 from the package.json before failing out? Here is the full stack of my two runs:

```
 Michael ~/PhET/git/chains (master)
 $ grunt rc --brands=phet-io,phet --branch=1.17
Running "rc" task
(Forwarding task to perennial)
Running "rc" task
Release branch 1.17 does not exist. Create it? [y/N]?y
info: Setting version from package.json for chains to 1.17.0-rc.0
info: git add package.json on chains
info: git commit on chains with message:
Bumping version to 1.17.0-rc.0
info: git push on chains to 1.17
info: npm update on chains
info: npm update on chipper
info: building chains
info: Copying ../chains/build/phet/dependencies.json to ../chains/dependencies.json
info: git add dependencies.json on chains
info: git commit on chains with message:
updated dependencies.json for version 1.17.0-rc.0
info: git push on chains to 1.17
info: git checkout master on chains
info: Setting version from package.json for chains to 1.18.0-dev.0
info: git add package.json on chains
info: git commit on chains with message:
Bumping version to 1.18.0-dev.0
info: git push on chains to master
info: git checkout 1.17 on chains
info: checking out shas for chains 1.17
info: git checkout 1.17 on chains
info: git pull on chains
info: getting dependencies.json for chains
info: checking out dependencies for chains
info: git checkout 928741cfc8fe804334d5b35292140314511f8678 on assert
info: git checkout 90e043121a55a3bed04900dadff8068d2383d860 on axon
info: git checkout 89d28f6309a83eb51b6c1fc0130e76ad7935f09e on brand
info: git checkout 5acde14577d443ab34e23448b51d0a352f7ccf3c on chipper
info: git checkout baee2231b9941305cb39a8df62523391c682bf3f on dot
info: git checkout 8417ee3ea84101b80309c96cbad7bcac21cf2929 on joist
info: git checkout 46439cb666c16016b95ca0b44a3f828bc1bc1275 on kite
info: git checkout 06a818a4924b960a6e572a1e9b2a89d21f048726 on phet-core
info: git checkout 3cd9f326c8f7dd4281519779dd79b07e46f0b6d0 on phet-io
info: git checkout 537086164a1436619416e26771f057f85f4db626 on phet-io-wrapper-classroom-activity
info: git checkout e4ebc3ff6ab38cc03051d8040c203a2162246328 on phet-io-wrapper-hookes-law-energy
info: git checkout 1527afd6b3351994af48514b6253e2b817e4f428 on phet-io-wrapper-lab-book
info: git checkout a81ebf9afe129636e4ccafa12db53b2486ba0386 on phet-io-wrappers
info: git checkout add1dbb2b874b24776acb78817a8820c4ff400ce on phetcommon
info: git checkout 1f2322e4cab5658d4134715f00e12e5a741b2b9f on query-string-machine
info: git checkout 71b38c1b2bd7fff7c402f449856944a5dc043ed2 on scenery
info: git checkout 287363abcf55edd051e75065cc80fd787f53cdb9 on scenery-phet
info: git checkout ded365aa2df5026200b20b13b9a9027d5a25215e on sherpa
info: git checkout 9c9b23fc927a1ebfa305124f3dfb3b4ac32316f1 on sun
info: git checkout f0b55e49fc9f4c0c22bb7b857711c586e2ab595e on tandem
info: npm update on chains
info: npm update on chipper
info: running [[ -d "/data/web/htdocs/dev/html/chains/1.17.0-rc.1" ]] && echo exists || echo not remotely on bayes.colorado.edu
>> Detected failure during deploy, reverting to master
info: checking out master for chains
info: getting dependencies.json for chains
info: git checkout master on assert
info: git checkout master on axon
info: git checkout master on brand
info: git checkout master on chains
info: git checkout master on chipper
info: git checkout master on dot
info: git checkout master on joist
info: git checkout master on kite
info: git checkout master on phet-core
info: git checkout master on phet-io
info: git checkout master on phet-io-wrapper-classroom-activity
info: git checkout master on phet-io-wrapper-hookes-law-energy
info: git checkout master on phet-io-wrapper-lab-book
info: git checkout master on phet-io-wrappers
info: git checkout master on phetcommon
info: git checkout master on query-string-machine
info: git checkout master on scenery
info: git checkout master on scenery-phet
info: git checkout master on sherpa
info: git checkout master on sun
info: git checkout master on tandem
info: npm update on chains
info: npm update on chipper
Fatal error: Perennial task failed:
Error: Cannot reach the dev server.  Check that you have an internet connection and that you are either on campus or on the VPN.
  at devSsh.then.catch.reason (C:\Users\Michael\PhET\git\perennial\js\common\devDirectoryExists.js:34:13)
  at process._tickCallback (internal/process/next_tick.js:68:7)

Full Error details:
{}
Fatal error: perennial grunt "--repo=chains" "rc" "--brands=phet-io,phet" "--branch=1.17" failed with code 1

 Michael ~/PhET/git/chains (master)
 $ grunt rc --brands=phet-io,phet --branch=1.17
Running "rc" task
(Forwarding task to perennial)
Running "rc" task
info: checking out shas for chains 1.17
info: git checkout 1.17 on chains
info: git pull on chains
info: getting dependencies.json for chains
info: checking out dependencies for chains
info: git checkout 928741cfc8fe804334d5b35292140314511f8678 on assert
info: git checkout 90e043121a55a3bed04900dadff8068d2383d860 on axon
info: git checkout 89d28f6309a83eb51b6c1fc0130e76ad7935f09e on brand
info: git checkout 5acde14577d443ab34e23448b51d0a352f7ccf3c on chipper
info: git checkout baee2231b9941305cb39a8df62523391c682bf3f on dot
info: git checkout 8417ee3ea84101b80309c96cbad7bcac21cf2929 on joist
info: git checkout 46439cb666c16016b95ca0b44a3f828bc1bc1275 on kite
info: git checkout 06a818a4924b960a6e572a1e9b2a89d21f048726 on phet-core
info: git checkout 3cd9f326c8f7dd4281519779dd79b07e46f0b6d0 on phet-io
info: git checkout 537086164a1436619416e26771f057f85f4db626 on phet-io-wrapper-classroom-activity
info: git checkout e4ebc3ff6ab38cc03051d8040c203a2162246328 on phet-io-wrapper-hookes-law-energy
info: git checkout 1527afd6b3351994af48514b6253e2b817e4f428 on phet-io-wrapper-lab-book
info: git checkout a81ebf9afe129636e4ccafa12db53b2486ba0386 on phet-io-wrappers
info: git checkout add1dbb2b874b24776acb78817a8820c4ff400ce on phetcommon
info: git checkout 1f2322e4cab5658d4134715f00e12e5a741b2b9f on query-string-machine
info: git checkout 71b38c1b2bd7fff7c402f449856944a5dc043ed2 on scenery
info: git checkout 287363abcf55edd051e75065cc80fd787f53cdb9 on scenery-phet
info: git checkout ded365aa2df5026200b20b13b9a9027d5a25215e on sherpa
info: git checkout 9c9b23fc927a1ebfa305124f3dfb3b4ac32316f1 on sun
info: git checkout f0b55e49fc9f4c0c22bb7b857711c586e2ab595e on tandem
info: npm update on chains
info: npm update on chipper
info: running [[ -d "/data/web/htdocs/dev/html/chains/1.17.0-rc.1" ]] && echo exists || echo not remotely on bayes.colorado.edu
Deploy 1.17.0-rc.1 to bayes.colorado.edu [y/N]?n
Fatal error: Aborted rc deployment
Fatal error: perennial grunt "--repo=chains" "rc" "--brands=phet-io,phet" "--branch=1.17" failed with code 1

**Comment by jonathanolson** [comment]
> 1.16.0-dev.*

That's not a valid version (it should be a number there), so maybe it should have immediately errored out instead?

> but kept it in the package.json when the process failed out

It reverted to what it thought the parsed version was. Since it parsed incorrectly, this seems like a side-effect result.

It looks like the parsing should include the entire version string, not just matching a part of it.

**Comment by samreid** [comment]
> 1.16.0-dev.*

I suspect @zepumph meant `1.16.0-dev.16`.

**Comment by jonathanolson** [comment]
Ahh I misread. I'll look into it, but it seems fundamentally wrong having dev versions on a release branch.

**Comment by jonathanolson** [comment]
I just tested the same thing (moved it to a temporary branch name) and it properly errored out with:
```
Fatal error: Aborted rc deployment since the version number cannot be incremented safely (testType:dev)
```

**Comment by jonathanolson** [comment]
Hmm, wait. It looks like there was no 1.17 branch before?

**Comment by samreid** [comment]
Does the build process create the branch or assume you have already created it?

**Comment by jonathanolson** [comment]
Ok sorry, I think I figured things out.

> We were surprised to see that it proceeded to try to deploy 1.17.0-rc.0. Is that correct?

I doesn't ever try to deploy rc.0 that I saw, can you point me to it?

> Here is another problem (it should probably be in another issue): furthermore, when I wasn't on vpn, it didn't create/deploy rc.0, but kept it in the package.json when the process failed out, so the next time, when I ran the same command, it tried to deploy rc.1.
>
> Shouldn't the process have reverted rc.0 from the package.json before failing out? Here is the full stack of my two runs:

The deployment was also used to create a release branch. That isn't revertible, and is an initial step that successfully completed (and should set the version to rc.0). Then deploys would deploy to rc.1, etc. Reverting the creation of a release branch is probably just removing the branch remotely and locally from git.

> Does the build process create the branch or assume you have already created it?

It looks like it detected the branch didn't exist, so prompted to create it:

> Release branch 1.17 does not exist. Create it? [y/N]?y

**Comment by zepumph** [comment]
Alright, let me try to sum up the knowledge in this issue. @jonathanolson, it seems like when you create a release branch as part of a first rc deploy, it sets the version to rc.0 as a placeholder. 

Even if the rc deploy fails, the release branch won't revert. And in our case since the rc failed, it didn't get to the point where rc.0 was bumped up to rc.1 for the initial deploy in the branch. 

In addition, reverting the branch creation when rc deploy fails is not supported in chipper 2.0.

Now that I understand the expected behavior, everything sounds good to me. I agree that it is easy enough revert a release branch your self if needed.

I'm ready to close this issue. Thank you @jonathanolson for explaining.

**Comment by zepumph** [comment]
Please reopen if there is anything else.
