### ISSUE TITLE
`grunt dev` fails after incrementing version number

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#699]
`grunt dev` fails if the remote has changes that you don't have locally, but not until _after_ it has incremented and pushed the version number.  I have no local changes.  

Two questions:

(1) Should it be possible to publish without consulting remote changes?
(2) Should we check for remote changes (and other possible conflicts?) before incrementing version number? 

Example:

```
 grunt dev --brands=phet --message="baseline"
Running "dev" task
(Forwarding task to perennial)
Running "dev" task
info: linting graphing-quadratics
info: running [[ -d "/data/web/htdocs/dev/html/graphing-quadratics" ]] && echo exists || echo not remotely on bayes.colorado.edu
info: running [[ -d "/data/web/htdocs/dev/html/graphing-quadratics/1.0.0-dev.3" ]] && echo exists || echo not remotely on bayes.colorado.edu
Deploy 1.0.0-dev.3 to bayes.colorado.edu [y/N]?y
Are you using the CU Boulder network (on campus or via VPN)? [y/N]?y
info: Setting version from package.json for graphing-quadratics to 1.0.0-dev.3
info: git add package.json on graphing-quadratics
info: git commit on graphing-quadratics with message:
Bumping version to 1.0.0-dev.3, baseline
info: git push on graphing-quadratics to master
Fatal error: Perennial task failed:
Error: git push -u origin master in ../graphing-quadratics failed with exit code 1 and stdout:

  at ChildProcess.process.on.code (/Users/cmalley/PhET/GitHub/perennial/js/common/execute.js:72:17)
  at emitTwo (events.js:126:13)
  at ChildProcess.emit (events.js:214:7)
  at maybeClose (internal/child_process.js:925:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

Full Error details:
{
  "cmd": "git",
  "args": [
    "push",
    "-u",
    "origin",
    "master"
  ],
  "cwd": "../graphing-quadratics",
  "stdout": "",
  "stderr": "To https://github.com/phetsims/graphing-quadratics.git\n ! [rejected]        master -> master (fetch first)\nerror: failed to push some refs to 'https://github.com/phetsims/graphing-quadratics.git'\nhint: Updates were rejected because the remote contains work that you do\nhint: not have locally. This is usually caused by another repository pushing\nhint: to the same ref. You may want to first integrate the remote changes\nhint: (e.g., 'git pull ...') before pushing again.\nhint: See the 'Note about fast-forwards' in 'git push --help' for details.\n",
  "code": 1
}
Fatal error: perennial grunt "--repo=graphing-quadratics" "dev" "--brands=phet" "--message=baseline" failed with code 1
```

**Comment by jonathanolson** [comment]
There are a few options:

- Dev deploys pull master first? Presumably we'd need to pull all dependencies too to be consistent, and it seems like things could "suddenly" break.
- Dev deploys check for whether the sim repository is out-of-date, and fail out if so.

I'd prefer the "fail out" option personally, with a helpful message.

**Comment by pixelzoom** [comment]
+1 for the "fail out" option.

**Comment by jonathanolson** [comment]
Implemented. @pixelzoom feel free to verify or just close.
