### ISSUE TITLE
Linting now fails if you don't have phet-io repos checked out

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#748]
A recent change to our linting system causes it to fail if it doesn't match at least one file in the directory.  A user in the google group reported:

https://groups.google.com/forum/#!topic/developing-interactive-simulations-in-html5/9QouIghG2wg

Hi,

I've followed creating a new sim step-by-step. However, when I try to rebuild the sim, I get an error about phet-io. I couldn't find a repository for phet-io.

Any clues?

~/Projects/phetsims/mysim$ grunt
Running "lint-all" task
Fatal error: Perennial task failed:
Error: No files matching 'phet-io' were found.
  at resolvedPathsByGlobPattern.reduce (/Users/joe/Projects/phetsims/chipper/node_modules/eslint/lib/util/glob-utils.js:244:19)
  at Array.reduce (<anonymous>:null:null)
  at Object.listFilesToProcess (/Users/joe/Projects/phetsims/chipper/node_modules/eslint/lib/util/glob-utils.js:242:59)
  at CLIEngine.executeOnFiles (/Users/joe/Projects/phetsims/chipper/node_modules/eslint/lib/cli-engine.js:586:36)
  at module.exports (/Users/joe/Projects/phetsims/chipper/js/grunt/lint.js:70:22)
  at grunt.registerTask.wrapTask (/Users/joe/Projects/phetsims/chipper/js/grunt/Gruntfile.js:236:5)
  at Object.<anonymous> (/Users/joe/Projects/phetsims/chipper/js/grunt/Gruntfile.js:90:13)
  at Object.thisTask.fn (/Users/joe/Projects/phetsims/mysim/node_modules/grunt/lib/grunt/task.js:70:16)
  at Object.<anonymous> (/Users/joe/Projects/phetsims/mysim/node_modules/grunt/lib/util/task.js:294:30)
  at Task.runTaskFn (/Users/joe/Projects/phetsims/mysim/node_modules/grunt/lib/util/task.js:244:24)
  at Task.<anonymous> (/Users/joe/Projects/phetsims/mysim/node_modules/grunt/lib/util/task.js:293:12)
  at /Users/joe/Projects/phetsims/mysim/node_modules/grunt/lib/util/task.js:220:11
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)

Full Error details:
{
  "messageTemplate": "file-not-found",
  "messageData": {
    "pattern": "phet-io"
  }
}

**Comment by samreid** [comment]
I was able to reproduce the problem by temporarily renaming my phet-io directories.

In the above commit, I restricted linting to directories that exist.  This resolves the reported problem.  I'm not 100% sure this is the right way to solve it though, and would like @zepumph to double check.  Also, after fixing this, there is a downstream problem in reportMedia.

**Comment by samreid** [comment]
After the above commit, builds can once again complete even when phet-io repos are not checked out.  @zepumph can you please see if there is a better solution for this problem?

**Comment by zepumph** [comment]
Yes this is great thanks.
