### ISSUE TITLE
Dependencies not committed when deploying RC

### ISSUE THREAD

**Issue by chrisklus** [phetsims/chipper#789]
```
chk@voyager:~/phetsims/energy-forms-and-changes$ grunt rc --branch=1.2 --brands=phet
Running "rc" task
(Forwarding task to perennial)
Running "rc" task
Release branch 1.2 does not exist. Create it? [y/N]?y
info: Setting the release branch version to rc.0 so it will auto-increment to rc.1 for the first RC deployment
info: git checkout -b 1.2 on energy-forms-and-changes
info: Setting version from package.json for energy-forms-and-changes to 1.2.0-rc.0
info: git add package.json on energy-forms-and-changes
info: git commit on energy-forms-and-changes with message:
Bumping version to 1.2.0-rc.0
info: git push on energy-forms-and-changes to 1.2
info: npm update on energy-forms-and-changes
info: npm update on chipper
info: building energy-forms-and-changes
info: Copying ../energy-forms-and-changes/build/phet/dependencies.json to ../energy-forms-and-changes/dependencies.json
info: git add dependencies.json on energy-forms-and-changes
info: git commit on energy-forms-and-changes with message:
updated dependencies.json for version 1.2.0-rc.0
info: git push on energy-forms-and-changes to 1.2
info: git checkout master on energy-forms-and-changes
Fatal error: Perennial task failed:
Error: git checkout master in ../energy-forms-and-changes failed with exit code 1 and stdout:

  at ChildProcess.process.on.code (/Users/chk/phetsims/perennial/js/common/execute.js:72:17)
  at ChildProcess.emit (events.js:197:13)
  at ChildProcess.EventEmitter.emit (domain.js:439:20)
  at maybeClose (internal/child_process.js:978:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)

Full Error details:
{
  "cmd": "git",
  "args": [
    "checkout",
    "master"
  ],
  "cwd": "../energy-forms-and-changes",
  "stdout": "",
  "stderr": "error: Your local changes to the following files would be overwritten by checkout:\n\tdependencies.json\nPlease commit your changes or stash them before you switch branches.\nAborting\n",
  "code": 1
}
Fatal error: perennial grunt "--repo=energy-forms-and-changes" "rc" "--branch=1.2" "--brands=phet" failed with code 1
```

When I checked out my working copy after this error message, dependencies.json looked correct, but all of its content was an uncommitted addition. With a clean working copy on branch 1.2, the file was blank.

@samreid took a look at it with me, and we copied dependencies.json from the build directory, committed it, and then tried the RC again and it worked.

@jonathanolson or @mattpen have you seen this before?

**Comment by jonathanolson** [comment]
I haven't. Is there any way it's possible to reproduce?

**Comment by mattpen** [comment]
I haven't seen this either

**Comment by chrisklus** [comment]
@jonathanolson hard to know without creating another RC haha, but this has never happened to me before so I kind of doubt it. I'm not sure how to proceed besides deferring and seeing if it ever comes up again. What do you think?

**Comment by jonathanolson** [comment]
Sounds good to me.
