### ISSUE TITLE
TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#948]
```
arithmetic : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (arithmetic, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 4107ms
>> Production minification complete: 27571ms (1813751 bytes)
>> Debug minification complete: 1ms (5504071 bytes)
Building brand: phet-io
>> Webpack build complete: 2938ms
>> Production minification complete: 24214ms (1829200 bytes)
>> Debug minification complete: 25568ms (2065571 bytes)
Fatal error: Perennial task failed:
TypeError: Cannot read property 'endsWith' of undefined
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1590275811877/chipper/js/grunt/phet-io/generatePhetioAPI.js:19:37)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1590275811877/chipper/js/grunt/phet-io/copySupplementalPhetioFiles.js:269:27)
at process._tickCallback (internal/process/next_tick.js:68:7)

Full Error details:
{}

(node:92770) ExperimentalWarning: The fs.promises API is experimental
Snapshot from 5/23/2020, 5:16:51 PM

```

**Comment by samreid** [comment]
This is caused by a missing `localTestingURL`.  We will need to set up the in-process node server to get this to work.  I re-disabled this call until then.

**Comment by samreid** [comment]
I added the in-process server as part of https://github.com/phetsims/phet-io/issues/1664, closing.
