### ISSUE TITLE
Error: Navigation failed because browser has disconnected! during build on CT

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#958]
This occurred on a few CT cells in the last few days.  I can't reproduce the problem on my side, but @zepumph says he has seen it about 50% of the time during 2 tests.  This was originally pointed out by @pixelzoom 

```
energy-forms-and-changes : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (energy-forms-and-changes, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 4750ms
>> Unused string: key=normal, value=Normal
>> Unused string: key=fastForward, value=Fast Forward
>> Production minification complete: 35949ms (3445779 bytes)
>> Debug minification complete: 0ms (7707333 bytes)
Building brand: phet-io
>> Webpack build complete: 4221ms
>> Unused string: key=normal, value=Normal
>> Unused string: key=fastForward, value=Fast Forward
>> Production minification complete: 30352ms (3469744 bytes)
>> Debug minification complete: 31344ms (3727803 bytes)
Fatal error: Perennial task failed:
Error: Navigation failed because browser has disconnected!
at CDPSession.LifecycleWatcher._eventListeners.helper.addEventListener (/data/share/phet/continuous-testing/ct-snapshots/1593721726209/chipper/node_modules/puppeteer/lib/LifecycleWatcher.js:46:107)
at CDPSession.emit (events.js:198:13)
at CDPSession._onClosed (/data/share/phet/continuous-testing/ct-snapshots/1593721726209/chipper/node_modules/puppeteer/lib/Connection.js:215:10)
at Connection._onClose (/data/share/phet/continuous-testing/ct-snapshots/1593721726209/chipper/node_modules/puppeteer/lib/Connection.js:138:15)
at WebSocketTransport._ws.addEventListener.event (/data/share/phet/continuous-testing/ct-snapshots/1593721726209/chipper/node_modules/puppeteer/lib/WebSocketTransport.js:48:22)
at WebSocket.onClose (/data/share/phet/continuous-testing/ct-snapshots/1593721726209/chipper/node_modules/ws/lib/event-target.js:124:16)
at WebSocket.emit (events.js:198:13)
at WebSocket.emitClose (/data/share/phet/continuous-testing/ct-snapshots/1593721726209/chipper/node_modules/ws/lib/websocket.js:191:10)
at Socket.socketOnClose (/data/share/phet/continuous-testing/ct-snapshots/1593721726209/chipper/node_modules/ws/lib/websocket.js:850:15)
at Socket.emit (events.js:198:13)
at TCP._handle.close (net.js:606:12)

-- ASYNC --
at Frame.<anonymous> (/data/share/phet/continuous-testing/ct-snapshots/1593721726209/chipper/node_modules/puppeteer/lib/helper.js:111:15)
at Page.goto (/data/share/phet/continuous-testing/ct-snapshots/1593721726209/chipper/node_modules/puppeteer/lib/Page.js:672:49)
at Page.<anonymous> (/data/share/phet/continuous-testing/ct-snapshots/1593721726209/chipper/node_modules/puppeteer/lib/helper.js:112:23)
at Promise (/data/share/phet/continuous-testing/ct-snapshots/1593721726209/chipper/js/grunt/phet-io/generatePhetioAPI.js:95:18)
at process._tickCallback (internal/process/next_tick.js:68:7)

Full Error details:
{}
Snapshot from 7/2/2020, 2:28:46 PM
```

**Comment by samreid** [comment]
I worked with @jonathanolson and @zepumph and we cleaned up a few things, one in particular was the so-called "Promise constructor anti-pattern" described in https://stackoverflow.com/questions/43036229/is-it-an-anti-pattern-to-use-async-await-inside-of-a-new-promise-constructor.

We cannot reliably reproduce the problem, but we would like CT to have a look.  Local build looks OK after these changes.

**Comment by zepumph** [comment]
I pulled all, and on first phet-io build I still got a Navigation error. We'll keep working!

**Comment by samreid** [comment]
Is CT stalled?  That commit was pushed at 4:35pm yesterday, and CT reports `ERR` and last shas are from 2:30pm yesterday.  Co-assigning @jonathanolson for this part and also since he had expertise in helping look into this async/await problem.

**Comment by samreid** [comment]
I wonder if the problem is that we need to `await browser.close()` before resolve/reject?

**Comment by samreid** [comment]
If this doesn't fix it, perhaps we should rewrite this part to use `page.exposeFunction` instead of listening for the `console.log`

**Comment by samreid** [comment]
CT is not showing this problem in the latest column.  I'll put a calendar reminder to check it again in a few days.

**Comment by samreid** [comment]
It looks like this is fixed (unless it is obscured by https://github.com/phetsims/chipper/issues/959 ).  Closing for now.
