### ISSUE TITLE
CT ENOENT no such file or directory

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/chipper#959]
Showing up in several sims in CT
```
energy-forms-and-changes : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (energy-forms-and-changes, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 4707ms
>> Unused string: key=normal, value=Normal
>> Unused string: key=fastForward, value=Fast Forward
>> Production minification complete: 36595ms (3445824 bytes)
>> Debug minification complete: 0ms (7708435 bytes)
Building brand: phet-io
>> Webpack build complete: 4404ms
>> Unused string: key=normal, value=Normal
>> Unused string: key=fastForward, value=Fast Forward
>> Production minification complete: 35012ms (3469779 bytes)
>> Debug minification complete: 35609ms (3727604 bytes)
Fatal error: Perennial task failed:
Error: ENOENT: no such file or directory, scandir '../phet-io-client-guides/common/'
at Object.readdirSync (fs.js:790:3)
at Object.recurse (/data/share/phet/continuous-testing/ct-snapshots/1593879410237/chipper/node_modules/grunt/lib/grunt/file.js:194:6)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1593879410237/chipper/js/grunt/copyDirectory.js:32:14)
at handleClientGuides (/data/share/phet/continuous-testing/ct-snapshots/1593879410237/chipper/js/grunt/phet-io/copySupplementalPhetioFiles.js:406:3)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1593879410237/chipper/js/grunt/phet-io/copySupplementalPhetioFiles.js:277:3)
at process._tickCallback (internal/process/next_tick.js:68:7)

Full Error details:
{
"errno": -2,
"syscall": "scandir",
"code": "ENOENT",
"path": "../phet-io-client-guides/common/"
}
Snapshot from 7/4/2020, 10:16:50 AM
```

**Comment by samreid** [comment]
I took a quick look but wasn't able to figure it out, @zepumph or @chrisklus can you please take a look?

**Comment by pixelzoom** [comment]
`phet-io-client-guides/common/`  does not exist in GitHub.  Maybe someone forgot to add it from their working copy.

**Comment by zepumph** [comment]
Fixed with  https://github.com/phetsims/phet-io-client-guides/commit/670587861ca12f554da6693493cdac66024882a4, root issue is https://github.com/phetsims/phet-io-client-guides/issues/2. I forgot to push a commit made last Thursday. Sorry about that.

**Comment by zepumph** [comment]
Looks fixed on CT, closing
