### ISSUE TITLE
Phet-io Build fails on build-server due to need to npm prune and update in studio

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#961]
This is because of https://github.com/phetsims/studio/issues/120

I added a process to build studio, but it needs to make sure that local grunt is installed before doing that. Here is the build fail email:

<details>

```
Build failure: Build aborted,Error: grunt --allHTML --debugHTML --brands=phet,phet-io --locales=en in ../ph-scale failed with exit code 1 and stdout:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (ph-scale, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 2772ms
>> Production minification complete: 20332ms (1821331 bytes)
>> Debug minification complete: 1ms (5706108 bytes)
Building brand: phet-io
>> Webpack build complete: 2268ms
>> Production minification complete: 18324ms (1846938 bytes)
>> Debug minification complete: 18921ms (2095294 bytes)
Fatal error: Perennial task failed:
Error: grunt build in ../studio failed with exit code 99 and stdout:
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://secure-web.cisco.com/1CTMjQmWt_26JV3rTKS3-m1BiE9VBGygAJkNa2jJs4amyt6Wu53CfiXwLumnPRTUrYLXgcwul9Nqkq8tVacjTpGGmLjpOMem1ToftVdX7yR15LaJWbJpADf1Nj5mYHXoQFdXlqK3yAeASU0yl34-BTsWRV90tDwHFb4bIw1Depg_WukLyVDT8jsDIvJog3593-zMe2LGrdLTL4HPwT_5rqSCbZmvSTW4rtxPbcBowUCiCAHodPCVKHRSqdBelom5RGME2R8iu_aUJzI8PJmovZM7_u2Vezpt6LYQ27hOgL6ZAqQdoWlD6FcgBovU2vx1VeZblpu9J95Ba2uW70rUkGQ5LQllHoIT1tR9HQWIi6vGGkn5LcadzgZKMaXntYy_pCPUaTskg3ffI_uFjE60LZ0Mi7818et0SVX6doTE1AAFoNxcgcvU7FyBoWbAEhiVeSnWnB9TrZsLt7PDwF0X4-w/http%3A%2F%2Fgruntjs.com%2Fgetting-started

  at ChildProcess.<anonymous> (/data/share/phet/phet-repos/chipper/js/grunt/execute.js:77:17)
  at ChildProcess.emit (events.js:210:5)
  at maybeClose (internal/child_process.js:1021:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

Full Error details:
{
  "cmd": "grunt",
  "args": [
    "build"
  ],
  "cwd": "../studio",
  "stdout": "grunt-cli: The grunt command line interface (v1.2.0)\n\nFatal error: Unable to find local grunt.\n\nIf you're seeing this message, grunt hasn't been installed locally to\nyour project. For more information about installing and configuring grunt,\nplease see the Getting Started guide:\n\nhttp://secure-web.cisco.com/1CTMjQmWt_26JV3rTKS3-m1BiE9VBGygAJkNa2jJs4amyt6Wu53CfiXwLumnPRTUrYLXgcwul9Nqkq8tVacjTpGGmLjpOMem1ToftVdX7yR15LaJWbJpADf1Nj5mYHXoQFdXlqK3yAeASU0yl34-BTsWRV90tDwHFb4bIw1Depg_WukLyVDT8jsDIvJog3593-zMe2LGrdLTL4HPwT_5rqSCbZmvSTW4rtxPbcBowUCiCAHodPCVKHRSqdBelom5RGME2R8iu_aUJzI8PJmovZM7_u2Vezpt6LYQ27hOgL6ZAqQdoWlD6FcgBovU2vx1VeZblpu9J95Ba2uW70rUkGQ5LQllHoIT1tR9HQWIi6vGGkn5LcadzgZKMaXntYy_pCPUaTskg3ffI_uFjE60LZ0Mi7818et0SVX6doTE1AAFoNxcgcvU7FyBoWbAEhiVeSnWnB9TrZsLt7PDwF0X4-w/http%3A%2F%2Fgruntjs.com%2Fgetting-started\n",
  "code": 99
}
. Sim = ph-scale Version = 1.4.0-rc.1 Brands = phet,phet-io Locales = en Shas = {"comment":"# ph-scale 1.4.0-rc.1 Thu Jul 09 2020 15:15:09 GMT-0600 (Mountain Daylight Time)","assert":{"sha":"1a41cef653bbed1025af5768bea958d7e3e0f8ae","branch":"HEAD"},"axon":{"sha":"8bc3f59ee72919c98b53592fe07345f6c4b60e3a","branch":"HEAD"},"brand":{"sha":"83c51961edf5b255206c82de7d6f4df6b4ea41bc","branch":"HEAD"},"chipper":{"sha":"6861df56e2761aaa01321ec0a5c05af3f2cdb7ae","branch":"HEAD"},"dot":{"sha":"1039f4fbfbdb62bfaddf3c850d73b25b4a00cbde","branch":"HEAD"},"joist":{"sha":"97571821251dbe1d560c278d29d46d42f5a5d228","branch":"HEAD"},"kite":{"sha":"5f0afa9da2f562014d032b39a765310e0ed45a14","branch":"HEAD"},"nitroglycerin":{"sha":"419889d5d52004b54d09261c9f2aca42654d0c98","branch":"HEAD"},"ph-scale":{"sha":"fa3b17532aa4557cd84e421e4844ca7d4ad5dbc2","branch":"1.4"},"phet-core":{"sha":"acfa434b9152548931c134aae54e9fa3b41bed9b","branch":"HEAD"},"phet-io":{"sha":"e1cc610b07c5115aaf53b241d606e686049d23b5","branch":"HEAD"},"phet-io-client-guides":{"sha":"3b953f3a69aa03aa149741155ef1632ac39b13e0","branch":"HEAD"},"phet-io-wrappers":{"sha":"381100f95b37ebc96ce33cbd71496fcaa854501a","branch":"HEAD"},"phetcommon":{"sha":"15041ecb736904afe2a9b50bc78afea2ecb2bd3b","branch":"HEAD"},"phetmarks":{"sha":"84c64b71ee50c13b7453eb276513118c1525f7db","branch":"HEAD"},"query-string-machine":{"sha":"599036755406fff368d329f42f6c9f7613f9ce2c","branch":"HEAD"},"scenery":{"sha":"517ee0f088162fc6b43c76c694aea831317cd963","branch":"HEAD"},"scenery-phet":{"sha":"4607ed50beb843e3dbfbc219d73429ace9a35cb2","branch":"HEAD"},"sherpa":{"sha":"f2d6e320646c6e0b63d5c8c30cc34953629b25a8","branch":"HEAD"},"studio":{"sha":"2342913daac3049e3d448cbfa55eba096c644875","branch":"HEAD"},"sun":{"sha":"d02b85cde1eb4300c21dee814d2d021fcde5d501","branch":"HEAD"},"tambo":{"sha":"683753ba15fdcde540ce0b1fe08918e6f33e55a5","branch":"HEAD"},"tandem":{"sha":"b8f61d4f1bb734167117ac0fa0506712ee56db8d","branch":"HEAD"},"utterance-queue":{"sha":"c2b44d1ca355707b2c2bae2a173c6ad26b5e6613","branch":"HEAD"}}

```
</details>

**Comment by zepumph** [comment]
@pixelzoom mentioned it would be good to test this by using phet-io-test-sim.

**Comment by zepumph** [comment]
copySupplementalPhetioFiles now runs npm prune and update in studio before trying to build studio. I tested this with a new RC of phet-io-test-sim, and it built successfully. https://phet-dev.colorado.edu/html/phet-io-test-sim/1.4.0-rc.1/phet-io/wrappers/studio/

Closing
