### ISSUE TITLE
Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#993]
This is showing up on every build we do with grunt since upgrading to Node14. @samreid, @jessegreenberg and I have all encountered it. Tracing the stack, it looks like it is from chipper's Gruntfile -> findDuplicates -> `jscpd`. It seems like everything else is internal to that module. I checked the versions of jscpd available. We are using `"jscpd": "^0.6.18"`, and the current npm version is `3.3.19`. 

Questions for this issue:

* Can we delete findDuplicates all together? That would remove this dependency. Likely related to https://github.com/phetsims/chipper/issues/526.
* In lieu of that easy option, we can upgrade jscpd?

Full stack trace:

```
 Michael ~/PhET/git/friction (master)
 $  node --trace-warnings node_modules/grunt/bin/grunt
(node:27344) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
  at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
  at Object.get (internal/modules/cjs/loader.js:664:5)
  at Object.exports.setLevels (C:\Users\Michael\PhET\git\chipper\node_modules\winston\lib\winston\common.js:35:14)
  at Object.<anonymous> (C:\Users\Michael\PhET\git\chipper\node_modules\winston\lib\winston.js:83:8)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (C:\Users\Michael\PhET\git\chipper\node_modules\coffeescript\lib\coffee-script\register.js:45:36)
  at Function.Module._load (internal/modules/cjs/loader.js:769:14)
  at Module.require (internal/modules/cjs/loader.js:952:19)
  at require (internal/modules/cjs/helpers.js:88:18)
  at Object.<anonymous> (C:\Users\Michael\PhET\git\chipper\node_modules\jscpd\lib\jscpd.js:5:12)
  at Object.<anonymous> (C:\Users\Michael\PhET\git\chipper\node_modules\jscpd\lib\jscpd.js:91:4)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (C:\Users\Michael\PhET\git\chipper\node_modules\coffeescript\lib\coffee-script\register.js:45:36)
  at Function.Module._load (internal/modules/cjs/loader.js:769:14)
  at Module.require (internal/modules/cjs/loader.js:952:19)
  at require (internal/modules/cjs/helpers.js:88:18)
  at Object.<anonymous> (C:\Users\Michael\PhET\git\chipper\node_modules\jscpd\index.js:1:13)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (C:\Users\Michael\PhET\git\chipper\node_modules\coffeescript\lib\coffee-script\register.js:45:36)
  at Function.Module._load (internal/modules/cjs/loader.js:769:14)
  at Module.require (internal/modules/cjs/loader.js:952:19)
  at require (internal/modules/cjs/helpers.js:88:18)
  at Object.<anonymous> (C:\Users\Michael\PhET\git\chipper\js\grunt\findDuplicates.js:23:15)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (C:\Users\Michael\PhET\git\chipper\node_modules\coffeescript\lib\coffee-script\register.js:45:36)
  at Function.Module._load (internal/modules/cjs/loader.js:769:14)
  at Module.require (internal/modules/cjs/loader.js:952:19)
  at require (internal/modules/cjs/helpers.js:88:18)
  at Object.<anonymous> (C:\Users\Michael\PhET\git\chipper\js\grunt\Gruntfile.js:16:24)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (C:\Users\Michael\PhET\git\friction\node_modules\coffeescript\lib\coffee-script\register.js:45:36)
  at Function.Module._load (internal/modules/cjs/loader.js:769:14)
  at Module.require (internal/modules/cjs/loader.js:952:19)
  at require (internal/modules/cjs/helpers.js:88:18)
  at Object.<anonymous> (C:\Users\Michael\PhET\git\friction\Gruntfile.js:6:18)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (C:\Users\Michael\PhET\git\friction\node_modules\coffeescript\lib\coffee-script\register.js:45:36)
  at Function.Module._load (internal/modules/cjs/loader.js:769:14)
  at Module.require (internal/modules/cjs/loader.js:952:19)
  at require (internal/modules/cjs/helpers.js:88:18)
  at loadTask (C:\Users\Michael\PhET\git\friction\node_modules\grunt\lib\grunt\task.js:313:10)
  at Task.task.init (C:\Users\Michael\PhET\git\friction\node_modules\grunt\lib\grunt\task.js:434:5)
  at Object.grunt.tasks (C:\Users\Michael\PhET\git\friction\node_modules\grunt\lib\grunt.js:111:8)
  at Object.module.exports [as cli] (C:\Users\Michael\PhET\git\friction\node_modules\grunt\lib\grunt\cli.js:27:9)
  at Object.<anonymous> (C:\Users\Michael\PhET\git\friction\node_modules\grunt\node_modules\grunt-cli\bin\grunt:44:20)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (internal/modules/cjs/loader.js:928:32)
  at Function.Module._load (internal/modules/cjs/loader.js:769:14)
  at Module.require (internal/modules/cjs/loader.js:952:19)
  at require (internal/modules/cjs/helpers.js:88:18)
  at Object.<anonymous> (C:\Users\Michael\PhET\git\friction\node_modules\grunt\bin\grunt:3:1)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (internal/modules/cjs/loader.js:928:32)
  at Function.Module._load (internal/modules/cjs/loader.js:769:14)
  at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
  at internal/main/run_main_module.js:17:47

```

Similar to https://github.com/phetsims/chipper/issues/992 I think. 

@ariel-phet to assign and prioritize. This is just a warning, it doesn't effect our workflow or cause problems (yet?).

**Comment by ariel-phet** [comment]
Marking as high priority for very quick discussion (and seeing if we have a volunteer!)

**Comment by chrisklus** [comment]
From 11/12/20 dev meeting, we decided that findDuplicates does not seem to be used and can be omitted. @samreid volunteered to do so, thanks!

**Comment by samreid** [comment]
Removed and tested by running grunt build and grunt update, closing.

**Comment by zepumph** [comment]
There seems to be another usage of the npm library causing this issue. After pull all, I can still get this warning by loading perennial's gruntfile, for example with `grunt print-phet-io-files`. 

Running with `--trace-warnings` indicates that our version of `winston` seems to be the issue.  I created https://github.com/phetsims/perennial/issues/201.
