### ISSUE TITLE
Chipper should assert that non a11y strings aren't in nested string file objects

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#999]
From https://github.com/phetsims/energy-skate-park/issues/317, nested strings in json files are not supported for translation. During dev meeting today, it was noted that an assertion during build would help catch this early.

**Comment by zepumph** [comment]
My guess is that something in getStringMap that is hard coded to allow `a11y` nesting, but nothing else, would be the place to start.

**Comment by zepumph** [comment]
This solution works, but it is at load time. I feel like it would be better to have it be on build.

```diff
Index: chipper/js/load-unbuilt-strings.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/chipper/js/load-unbuilt-strings.js b/chipper/js/load-unbuilt-strings.js
--- a/chipper/js/load-unbuilt-strings.js	(revision cb3ab08a98926ed8e8ade8de0ffa53cadf1f11b5)
+++ b/chipper/js/load-unbuilt-strings.js	(date 1611599074014)
@@ -50,17 +50,20 @@
     phet.chipper.strings[ locale ] = phet.chipper.strings[ locale ] || {};
     const localeStringMap = phet.chipper.strings[ locale ];
 
-    const recurse = ( path, object ) => {
+    const recurse = ( path, object, stackLevel ) => {
       Object.keys( object ).forEach( key => {
         if ( key === 'value' ) {
+          if ( stackLevel > 1 && !path.startsWith( 'a11y' ) ) {
+            throw new Error( `nested strings are not allowed outside of a11y object for key: ${requirejsNamespace}/${path}` );
+          }
           localeStringMap[ `${stringKeyPrefix}${path}` ] = object.value;
         }
         else if ( object[ key ] && typeof object[ key ] === 'object' ) {
-          recurse( `${path}${path.length ? '.' : ''}${key}`, object[ key ] );
+          recurse( `${path}${path.length ? '.' : ''}${key}`, object[ key ], stackLevel + 1 );
         }
       } );
     };
-    recurse( '', stringObject );
+    recurse( '', stringObject, 0 );
   };
 
   /**
@@ -81,7 +84,7 @@
       try {
         json = JSON.parse( request.responseText );
       }
-      catch ( e ) {
+      catch( e ) {
         console.log( `Could not parse string file for ${repo} with locale ${locale}, perhaps that translation does not exist yet?` );
       }
       if ( json ) {
```

But then I realized that we already have this assertion in ChipperStringUtils.js, it just was trying to use `global.assert` instead of requiring that module. Bug fixing being committed shortly.

**Comment by zepumph** [comment]
This will now error on build, but only for strings that are used by the sim. @jessegreenberg can you please test this out by trying to add nested strings, using it in your sim, and then building. I get an error like so when I do this for RAP:

```
Running "build" task
Building runnable repository (ratio-and-proportion, brands: phet)
Building brand: phet
>> Webpack build complete: 2607ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: nested strings are not allowed outside of a11y string object for key: range.other
  at Object.getStringFromMap (C:\Users\Michael\PhET\git\chipper\js\common\ChipperStringUtils.js:156:63)
  at C:\Users\Michael\PhET\git\chipper\js\grunt\getStringMap.js:207:46
  at Array.forEach (<anonymous>:null:null)
  at C:\Users\Michael\PhET\git\chipper\js\grunt\getStringMap.js:202:15
  at Array.forEach (<anonymous>:null:null)
  at C:\Users\Michael\PhET\git\chipper\js\grunt\getStringMap.js:201:23
  at Array.forEach (<anonymous>:null:null)
  at module.exports (C:\Users\Michael\PhET\git\chipper\js\grunt\getStringMap.js:153:24)
  at module.exports (C:\Users\Michael\PhET\git\chipper\js\grunt\buildRunnable.js:132:21)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at C:\Users\Michael\PhET\git\chipper\js\grunt\Gruntfile.js:254:11
  at wrap (C:\Users\Michael\PhET\git\chipper\js\grunt\Gruntfile.js:73:7)

Full Error details:
{
  "generatedMessage": false,
  "code": "ERR_ASSERTION",
  "expected": true,
  "operator": "=="
}
```

**Comment by zepumph** [comment]
There is one assertion now occurring for a MAL string. I'll commit a change, but is this a translated string key that needs some action in rosetta babel? @jessegreenberg please comment on if anything more is needed on the above. Marking high priority in case changing the string key was actually buggy.

**Comment by jessegreenberg** [comment]
Thanks for adding this! Indeed, that case is just like https://github.com/phetsims/energy-skate-park/issues/317. That string is currently not translatable so we will need to deploy a maintenance release with the commit you made to fix it.

**Comment by jessegreenberg** [comment]
A maintenance release of Molecules and Light was redeployed in https://github.com/phetsims/molecules-and-light/issues/379 and @KatieWoe helped me verify that the string is now translatable. No longer high priority.

@zepumph I think that shows this is working well, anything else for this issue?

**Comment by zepumph** [comment]
Oh sounds great. I think all is good to go. Closing
